// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Adyen.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Adyen.OpenApiClient.PaymentServiceV68.TechnicalCancel
{
    /// <summary>
    /// Builds and executes requests for operations under \PaymentService-v68\technicalCancel
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TechnicalCancelRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.PaymentServiceV68.TechnicalCancel.TechnicalCancelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TechnicalCancelRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PaymentService-v68/technicalCancel", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.PaymentServiceV68.TechnicalCancel.TechnicalCancelRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public TechnicalCancelRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/PaymentService-v68/technicalCancel", rawUrl)
        {
        }
        /// <summary>
        /// This endpoint allows you to cancel a payment if you do not have the PSP reference of the original payment request available.In your call, refer to the original payment by using the `reference` that you specified in your payment request.For more information, see [Technical cancel](https://docs.adyen.com/online-payments/classic-integrations/modify-payments/cancel#technical-cancel). &gt; This endpoint is part of our [classic API integration](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce). If using a [newer integration](https://docs.adyen.com/online-payments), use the [`/cancels`](https://docs.adyen.com/api-explorer/#/CheckoutService/cancels) endpoint under Checkout API instead.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.ModificationResult"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.PaymentServiceV68ServiceError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.PaymentServiceV68ServiceError">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.PaymentServiceV68ServiceError">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.PaymentServiceV68ServiceError">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.PaymentServiceV68ServiceError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Adyen.OpenApiClient.Models.ModificationResult?> PostAsync(global::Soenneker.Adyen.OpenApiClient.Models.TechnicalCancelRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Adyen.OpenApiClient.Models.ModificationResult> PostAsync(global::Soenneker.Adyen.OpenApiClient.Models.TechnicalCancelRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Adyen.OpenApiClient.Models.PaymentServiceV68ServiceError.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Adyen.OpenApiClient.Models.PaymentServiceV68ServiceError.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Adyen.OpenApiClient.Models.PaymentServiceV68ServiceError.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Adyen.OpenApiClient.Models.PaymentServiceV68ServiceError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Adyen.OpenApiClient.Models.PaymentServiceV68ServiceError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Adyen.OpenApiClient.Models.ModificationResult>(requestInfo, global::Soenneker.Adyen.OpenApiClient.Models.ModificationResult.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// This endpoint allows you to cancel a payment if you do not have the PSP reference of the original payment request available.In your call, refer to the original payment by using the `reference` that you specified in your payment request.For more information, see [Technical cancel](https://docs.adyen.com/online-payments/classic-integrations/modify-payments/cancel#technical-cancel). &gt; This endpoint is part of our [classic API integration](https://docs.adyen.com/online-payments/classic-integrations/api-integration-ecommerce). If using a [newer integration](https://docs.adyen.com/online-payments), use the [`/cancels`](https://docs.adyen.com/api-explorer/#/CheckoutService/cancels) endpoint under Checkout API instead.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Adyen.OpenApiClient.Models.TechnicalCancelRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Adyen.OpenApiClient.Models.TechnicalCancelRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.PaymentServiceV68.TechnicalCancel.TechnicalCancelRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Adyen.OpenApiClient.PaymentServiceV68.TechnicalCancel.TechnicalCancelRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Adyen.OpenApiClient.PaymentServiceV68.TechnicalCancel.TechnicalCancelRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
