// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.Activate;
using Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.ApiCredentials;
using Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.BillingEntities;
using Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.PaymentMethodSettings;
using Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.PayoutSettings;
using Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.ShippingLocations;
using Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.SplitConfigurations;
using Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.Stores;
using Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.TerminalLogos;
using Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.TerminalModels;
using Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.TerminalOrders;
using Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.TerminalProducts;
using Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.TerminalSettings;
using Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.Users;
using Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.Webhooks;
using Soenneker.Adyen.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \ManagementService-v3\merchants\{merchantId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithMerchantItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The activate property</summary>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.Activate.ActivateRequestBuilder Activate
        {
            get => new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.Activate.ActivateRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The apiCredentials property</summary>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.ApiCredentials.ApiCredentialsRequestBuilder ApiCredentials
        {
            get => new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.ApiCredentials.ApiCredentialsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The billingEntities property</summary>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.BillingEntities.BillingEntitiesRequestBuilder BillingEntities
        {
            get => new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.BillingEntities.BillingEntitiesRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The paymentMethodSettings property</summary>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.PaymentMethodSettings.PaymentMethodSettingsRequestBuilder PaymentMethodSettings
        {
            get => new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.PaymentMethodSettings.PaymentMethodSettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The payoutSettings property</summary>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.PayoutSettings.PayoutSettingsRequestBuilder PayoutSettings
        {
            get => new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.PayoutSettings.PayoutSettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The shippingLocations property</summary>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.ShippingLocations.ShippingLocationsRequestBuilder ShippingLocations
        {
            get => new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.ShippingLocations.ShippingLocationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The splitConfigurations property</summary>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.SplitConfigurations.SplitConfigurationsRequestBuilder SplitConfigurations
        {
            get => new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.SplitConfigurations.SplitConfigurationsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The stores property</summary>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.Stores.StoresRequestBuilder Stores
        {
            get => new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.Stores.StoresRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The terminalLogos property</summary>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.TerminalLogos.TerminalLogosRequestBuilder TerminalLogos
        {
            get => new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.TerminalLogos.TerminalLogosRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The terminalModels property</summary>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.TerminalModels.TerminalModelsRequestBuilder TerminalModels
        {
            get => new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.TerminalModels.TerminalModelsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The terminalOrders property</summary>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.TerminalOrders.TerminalOrdersRequestBuilder TerminalOrders
        {
            get => new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.TerminalOrders.TerminalOrdersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The terminalProducts property</summary>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.TerminalProducts.TerminalProductsRequestBuilder TerminalProducts
        {
            get => new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.TerminalProducts.TerminalProductsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The terminalSettings property</summary>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.TerminalSettings.TerminalSettingsRequestBuilder TerminalSettings
        {
            get => new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.TerminalSettings.TerminalSettingsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The users property</summary>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.Users.UsersRequestBuilder Users
        {
            get => new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.Users.UsersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The webhooks property</summary>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.Webhooks.WebhooksRequestBuilder Webhooks
        {
            get => new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.Webhooks.WebhooksRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.WithMerchantItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMerchantItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ManagementService-v3/merchants/{merchantId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.WithMerchantItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithMerchantItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ManagementService-v3/merchants/{merchantId}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the merchant account specified in the path. Your API credential must have access to the merchant account.To make this request, your API credential must have the following [roles](https://docs.adyen.com/development-resources/api-credentials#api-permissions):* Management API—Account read
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.Merchant"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3RestServiceError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3RestServiceError">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3RestServiceError">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3RestServiceError">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3RestServiceError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Adyen.OpenApiClient.Models.Merchant?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Adyen.OpenApiClient.Models.Merchant> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3RestServiceError.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3RestServiceError.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3RestServiceError.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3RestServiceError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3RestServiceError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Adyen.OpenApiClient.Models.Merchant>(requestInfo, global::Soenneker.Adyen.OpenApiClient.Models.Merchant.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the merchant account specified in the path. Your API credential must have access to the merchant account.To make this request, your API credential must have the following [roles](https://docs.adyen.com/development-resources/api-credentials#api-permissions):* Management API—Account read
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.WithMerchantItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.WithMerchantItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Merchants.Item.WithMerchantItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
