// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Adyen.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Adyen.OpenApiClient.TransferServiceV4.Grants.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \TransferService-v4\grants\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class GrantsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.TransferServiceV4.Grants.Item.GrantsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GrantsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/TransferService-v4/grants/{id}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.TransferServiceV4.Grants.Item.GrantsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public GrantsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/TransferService-v4/grants/{id}", rawUrl)
        {
        }
        /// <summary>
        /// Returns the details of a capital account specified in the path.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.CapitalGrant"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.TransferServiceV4RestServiceError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.TransferServiceV4RestServiceError">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.TransferServiceV4RestServiceError">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.TransferServiceV4RestServiceError">When receiving a 404 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.TransferServiceV4RestServiceError">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.TransferServiceV4RestServiceError">When receiving a 500 status code</exception>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Adyen.OpenApiClient.Models.CapitalGrant?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Adyen.OpenApiClient.Models.CapitalGrant> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Adyen.OpenApiClient.Models.TransferServiceV4RestServiceError.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Adyen.OpenApiClient.Models.TransferServiceV4RestServiceError.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Adyen.OpenApiClient.Models.TransferServiceV4RestServiceError.CreateFromDiscriminatorValue },
                { "404", global::Soenneker.Adyen.OpenApiClient.Models.TransferServiceV4RestServiceError.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Adyen.OpenApiClient.Models.TransferServiceV4RestServiceError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Adyen.OpenApiClient.Models.TransferServiceV4RestServiceError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Adyen.OpenApiClient.Models.CapitalGrant>(requestInfo, global::Soenneker.Adyen.OpenApiClient.Models.CapitalGrant.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Returns the details of a capital account specified in the path.
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.TransferServiceV4.Grants.Item.GrantsItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        [Obsolete("")]
        public global::Soenneker.Adyen.OpenApiClient.TransferServiceV4.Grants.Item.GrantsItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Adyen.OpenApiClient.TransferServiceV4.Grants.Item.GrantsItemRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
