// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.ChangeStatus;
using Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.CheckBalance;
using Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.Issue;
using Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.Load;
using Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.MergeBalance;
using Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.VoidTransaction;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Adyen.OpenApiClient.StoredValueServiceV46
{
    /// <summary>
    /// Builds and executes requests for operations under \StoredValueService-v46
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class StoredValueServiceV46RequestBuilder : BaseRequestBuilder
    {
        /// <summary>The changeStatus property</summary>
        public global::Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.ChangeStatus.ChangeStatusRequestBuilder ChangeStatus
        {
            get => new global::Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.ChangeStatus.ChangeStatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The checkBalance property</summary>
        public global::Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.CheckBalance.CheckBalanceRequestBuilder CheckBalance
        {
            get => new global::Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.CheckBalance.CheckBalanceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The issue property</summary>
        public global::Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.Issue.IssueRequestBuilder Issue
        {
            get => new global::Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.Issue.IssueRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The load property</summary>
        public global::Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.Load.LoadRequestBuilder Load
        {
            get => new global::Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.Load.LoadRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The mergeBalance property</summary>
        public global::Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.MergeBalance.MergeBalanceRequestBuilder MergeBalance
        {
            get => new global::Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.MergeBalance.MergeBalanceRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The voidTransaction property</summary>
        public global::Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.VoidTransaction.VoidTransactionRequestBuilder VoidTransaction
        {
            get => new global::Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.VoidTransaction.VoidTransactionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.StoredValueServiceV46RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StoredValueServiceV46RequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/StoredValueService-v46", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.StoredValueServiceV46.StoredValueServiceV46RequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public StoredValueServiceV46RequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/StoredValueService-v46", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
