// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ApplicationInfo : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The adyenLibrary property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.CommonField? AdyenLibrary { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.CommonField AdyenLibrary { get; set; }
#endif
        /// <summary>The adyenPaymentSource property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.CommonField? AdyenPaymentSource { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.CommonField AdyenPaymentSource { get; set; }
#endif
        /// <summary>The externalPlatform property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.ExternalPlatform? ExternalPlatform { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.ExternalPlatform ExternalPlatform { get; set; }
#endif
        /// <summary>The merchantApplication property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.CommonField? MerchantApplication { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.CommonField MerchantApplication { get; set; }
#endif
        /// <summary>The merchantDevice property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.MerchantDevice? MerchantDevice { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.MerchantDevice MerchantDevice { get; set; }
#endif
        /// <summary>The shopperInteractionDevice property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.ShopperInteractionDevice? ShopperInteractionDevice { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.ShopperInteractionDevice ShopperInteractionDevice { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.ApplicationInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.ApplicationInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.ApplicationInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "adyenLibrary", n => { AdyenLibrary = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CommonField>(global::Soenneker.Adyen.OpenApiClient.Models.CommonField.CreateFromDiscriminatorValue); } },
                { "adyenPaymentSource", n => { AdyenPaymentSource = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CommonField>(global::Soenneker.Adyen.OpenApiClient.Models.CommonField.CreateFromDiscriminatorValue); } },
                { "externalPlatform", n => { ExternalPlatform = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.ExternalPlatform>(global::Soenneker.Adyen.OpenApiClient.Models.ExternalPlatform.CreateFromDiscriminatorValue); } },
                { "merchantApplication", n => { MerchantApplication = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CommonField>(global::Soenneker.Adyen.OpenApiClient.Models.CommonField.CreateFromDiscriminatorValue); } },
                { "merchantDevice", n => { MerchantDevice = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.MerchantDevice>(global::Soenneker.Adyen.OpenApiClient.Models.MerchantDevice.CreateFromDiscriminatorValue); } },
                { "shopperInteractionDevice", n => { ShopperInteractionDevice = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.ShopperInteractionDevice>(global::Soenneker.Adyen.OpenApiClient.Models.ShopperInteractionDevice.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CommonField>("adyenLibrary", AdyenLibrary);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CommonField>("adyenPaymentSource", AdyenPaymentSource);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.ExternalPlatform>("externalPlatform", ExternalPlatform);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CommonField>("merchantApplication", MerchantApplication);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.MerchantDevice>("merchantDevice", MerchantDevice);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.ShopperInteractionDevice>("shopperInteractionDevice", ShopperInteractionDevice);
        }
    }
}
#pragma warning restore CS0618
