// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class AuthenticationResultResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The threeDS1Result property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.ThreeDS1Result? ThreeDS1Result { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.ThreeDS1Result ThreeDS1Result { get; set; }
#endif
        /// <summary>The threeDS2Result property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentServiceV68ThreeDS2Result? ThreeDS2Result { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentServiceV68ThreeDS2Result ThreeDS2Result { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.AuthenticationResultResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.AuthenticationResultResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.AuthenticationResultResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "threeDS1Result", n => { ThreeDS1Result = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.ThreeDS1Result>(global::Soenneker.Adyen.OpenApiClient.Models.ThreeDS1Result.CreateFromDiscriminatorValue); } },
                { "threeDS2Result", n => { ThreeDS2Result = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentServiceV68ThreeDS2Result>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentServiceV68ThreeDS2Result.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.ThreeDS1Result>("threeDS1Result", ThreeDS1Result);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentServiceV68ThreeDS2Result>("threeDS2Result", ThreeDS2Result);
        }
    }
}
#pragma warning restore CS0618
