// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class BalancePlatformConfiguration : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Specifies whether this payout schedule is automatically applied to new balance accounts.</summary>
        public bool? AutomaticApplication { get; set; }
        /// <summary>The balance platform to which the payout schedule applies.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BalancePlatformId { get; set; }
#nullable restore
#else
        public string BalancePlatformId { get; set; }
#endif
        /// <summary>The two-letter [ISO 3166-1 alpha-2](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-2) code of the country to which the payout schedule applies.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CountryCode { get; set; }
#nullable restore
#else
        public string CountryCode { get; set; }
#endif
        /// <summary>The date when the payout schedule was created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The three-character [ISO code](https://docs.adyen.com/development-resources/currency-codes) of the currency used for the payout schedule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Currency { get; set; }
#nullable restore
#else
        public string Currency { get; set; }
#endif
        /// <summary>The default description for payouts initiated by this payout schedule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultDescription { get; set; }
#nullable restore
#else
        public string DefaultDescription { get; set; }
#endif
        /// <summary>The defaultFrequency property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultFrequency { get; set; }
#nullable restore
#else
        public string DefaultFrequency { get; set; }
#endif
        /// <summary>The default value for date of the month or day of the week when payouts are initiated. Allowed only if `defaultFrequency` is **monthly** or **weekly**.Possible values if `defaultFrequency` is **monthly**: **[1 - 31]**.* If your specified date happens on a weekend, the payout is initiated on the next business day.* If your specified date (**29**, **30**, or **31**) does not exist in a month, the payout is initiated  on the last day of that month.Possible values if `defaultFrequency` is **weekly**: **[1 - 5]**.</summary>
        public int? DefaultFrequencyValue { get; set; }
        /// <summary>Your internal default reference for the payout schedule.When the payout schedule is applied to a balance account, this reference is also used for that payout schedule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultReference { get; set; }
#nullable restore
#else
        public string DefaultReference { get; set; }
#endif
        /// <summary>The default reference for beneficiary for payouts initiated by this payout schedule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? DefaultReferenceForBeneficiary { get; set; }
#nullable restore
#else
        public string DefaultReferenceForBeneficiary { get; set; }
#endif
        /// <summary>Specifies whether the payout schedule is enabled immediately after it is created.</summary>
        public bool? Enabled { get; set; }
        /// <summary>The unique identifier of the payout schedule for your balance platform.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The maximum amount that can be paid out from balance accounts that use this payout schedule.Default value: **0**, which means that there is no maximum limit.</summary>
        public long? MaxPayoutAmount { get; set; }
        /// <summary>The minimum amount that can be paid out from balance accounts that use this payout schedule.Default value: **0**.</summary>
        public long? MinPayoutAmount { get; set; }
        /// <summary>The type of payout schedule. This type indicates how fast funds are paid out to your user.Possible values:- **Standard**: The funds arrive in your user&apos;s transfer instrument two days after the funds are settled.- **Accelerated**: The funds arrive to your user&apos;s transfer instrument the day after the funds are settled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PayoutScheduleDescription { get; set; }
#nullable restore
#else
        public string PayoutScheduleDescription { get; set; }
#endif
        /// <summary>The amount of funds that must remain available in a balance account after an execution of the payout schedule. If the funds in the balance account are less than the retained amount, the execution is not initiated.Default value: **0**</summary>
        public long? RetainedAmount { get; set; }
        /// <summary>The date when the payout schedule was updated.</summary>
        public DateTimeOffset? UpdatedAt { get; set; }
        /// <summary>The default [settlement delay](https://docs.adyen.com/platforms/settle-funds/#settlement-delay) for this payout schedule.</summary>
        public int? UserSettlementDelay { get; set; }
        /// <summary>The userSettlementTime property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.LocalTime? UserSettlementTime { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.LocalTime UserSettlementTime { get; set; }
#endif
        /// <summary>The timezone of the `userSettlementTime`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? UserSettlementTimeZone { get; set; }
#nullable restore
#else
        public string UserSettlementTimeZone { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.Models.BalancePlatformConfiguration"/> and sets the default values.
        /// </summary>
        public BalancePlatformConfiguration()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.BalancePlatformConfiguration"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.BalancePlatformConfiguration CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.BalancePlatformConfiguration();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "automaticApplication", n => { AutomaticApplication = n.GetBoolValue(); } },
                { "balancePlatformId", n => { BalancePlatformId = n.GetStringValue(); } },
                { "countryCode", n => { CountryCode = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "currency", n => { Currency = n.GetStringValue(); } },
                { "defaultDescription", n => { DefaultDescription = n.GetStringValue(); } },
                { "defaultFrequency", n => { DefaultFrequency = n.GetStringValue(); } },
                { "defaultFrequencyValue", n => { DefaultFrequencyValue = n.GetIntValue(); } },
                { "defaultReference", n => { DefaultReference = n.GetStringValue(); } },
                { "defaultReferenceForBeneficiary", n => { DefaultReferenceForBeneficiary = n.GetStringValue(); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "maxPayoutAmount", n => { MaxPayoutAmount = n.GetLongValue(); } },
                { "minPayoutAmount", n => { MinPayoutAmount = n.GetLongValue(); } },
                { "payoutScheduleDescription", n => { PayoutScheduleDescription = n.GetStringValue(); } },
                { "retainedAmount", n => { RetainedAmount = n.GetLongValue(); } },
                { "updatedAt", n => { UpdatedAt = n.GetDateTimeOffsetValue(); } },
                { "userSettlementDelay", n => { UserSettlementDelay = n.GetIntValue(); } },
                { "userSettlementTime", n => { UserSettlementTime = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.LocalTime>(global::Soenneker.Adyen.OpenApiClient.Models.LocalTime.CreateFromDiscriminatorValue); } },
                { "userSettlementTimeZone", n => { UserSettlementTimeZone = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("automaticApplication", AutomaticApplication);
            writer.WriteStringValue("balancePlatformId", BalancePlatformId);
            writer.WriteStringValue("countryCode", CountryCode);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("currency", Currency);
            writer.WriteStringValue("defaultDescription", DefaultDescription);
            writer.WriteStringValue("defaultFrequency", DefaultFrequency);
            writer.WriteIntValue("defaultFrequencyValue", DefaultFrequencyValue);
            writer.WriteStringValue("defaultReference", DefaultReference);
            writer.WriteStringValue("defaultReferenceForBeneficiary", DefaultReferenceForBeneficiary);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteStringValue("id", Id);
            writer.WriteLongValue("maxPayoutAmount", MaxPayoutAmount);
            writer.WriteLongValue("minPayoutAmount", MinPayoutAmount);
            writer.WriteStringValue("payoutScheduleDescription", PayoutScheduleDescription);
            writer.WriteLongValue("retainedAmount", RetainedAmount);
            writer.WriteDateTimeOffsetValue("updatedAt", UpdatedAt);
            writer.WriteIntValue("userSettlementDelay", UserSettlementDelay);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.LocalTime>("userSettlementTime", UserSettlementTime);
            writer.WriteStringValue("userSettlementTimeZone", UserSettlementTimeZone);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
