// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>The type of the webhook you are configuring. Set to **balance**.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BalanceWebhookSettingInfoUpdate_type
    {
        [EnumMember(Value = "balance")]
        #pragma warning disable CS1591
        Balance,
        #pragma warning restore CS1591
    }
}
