// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum BalancePlatformServiceV2GetAccountHoldersIdTaxFormsFormTypeParameter
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "US1099k")]
        #pragma warning disable CS1591
        Us1099K,
        #pragma warning restore CS1591
        [EnumMember(Value = "US1099nec")]
        #pragma warning disable CS1591
        Us1099Nec,
        #pragma warning restore CS1591
    }
}
