// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>The type of the phone number.Possible values: **Landline**, **Mobile**, **SIP**, **Fax**.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum BalancePlatformServiceV2PhoneNumberPhoneType
    {
        [EnumMember(Value = "Fax")]
        #pragma warning disable CS1591
        Fax,
        #pragma warning restore CS1591
        [EnumMember(Value = "Landline")]
        #pragma warning disable CS1591
        Landline,
        #pragma warning restore CS1591
        [EnumMember(Value = "Mobile")]
        #pragma warning disable CS1591
        Mobile,
        #pragma warning restore CS1591
        [EnumMember(Value = "SIP")]
        #pragma warning disable CS1591
        Sip,
        #pragma warning restore CS1591
    }
}
