// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>The code for the status of the grant. Possible values:- **Pending**- **Active**- **Repaid**- **WrittenOff**- **Failed**- **Revoked**- **Requested**- **Reviewing**- **Approved**- **Rejected**- **Cancelled**</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CapitalServiceV1Status_code
    {
        [EnumMember(Value = "Pending")]
        #pragma warning disable CS1591
        Pending,
        #pragma warning restore CS1591
        [EnumMember(Value = "Active")]
        #pragma warning disable CS1591
        Active,
        #pragma warning restore CS1591
        [EnumMember(Value = "Repaid")]
        #pragma warning disable CS1591
        Repaid,
        #pragma warning restore CS1591
        [EnumMember(Value = "WrittenOff")]
        #pragma warning disable CS1591
        WrittenOff,
        #pragma warning restore CS1591
        [EnumMember(Value = "Failed")]
        #pragma warning disable CS1591
        Failed,
        #pragma warning restore CS1591
        [EnumMember(Value = "Revoked")]
        #pragma warning disable CS1591
        Revoked,
        #pragma warning restore CS1591
        [EnumMember(Value = "Requested")]
        #pragma warning disable CS1591
        Requested,
        #pragma warning restore CS1591
        [EnumMember(Value = "Reviewing")]
        #pragma warning disable CS1591
        Reviewing,
        #pragma warning restore CS1591
        [EnumMember(Value = "Approved")]
        #pragma warning disable CS1591
        Approved,
        #pragma warning restore CS1591
        [EnumMember(Value = "Rejected")]
        #pragma warning disable CS1591
        Rejected,
        #pragma warning restore CS1591
        [EnumMember(Value = "Cancelled")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
    }
}
