// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CapitalServiceV1Grant : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The balances property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1Balance? Balances { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1Balance Balances { get; set; }
#endif
        /// <summary>The counterparty property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1GrantCounterparty? Counterparty { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1GrantCounterparty Counterparty { get; set; }
#endif
        /// <summary>The unique identifier of the grant account that tracks this grant.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GrantAccountId { get; set; }
#nullable restore
#else
        public string GrantAccountId { get; set; }
#endif
        /// <summary>The unique identifier of the selected offer. Adyen uses the details of the selected offer to create a grant.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? GrantOfferId { get; set; }
#nullable restore
#else
        public string GrantOfferId { get; set; }
#endif
        /// <summary>The unique identifier of the grant reference.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The status property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1Status? Status { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1Status Status { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1Grant"/> and sets the default values.
        /// </summary>
        public CapitalServiceV1Grant()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1Grant"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1Grant CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1Grant();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "balances", n => { Balances = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1Balance>(global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1Balance.CreateFromDiscriminatorValue); } },
                { "counterparty", n => { Counterparty = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1GrantCounterparty>(global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1GrantCounterparty.CreateFromDiscriminatorValue); } },
                { "grantAccountId", n => { GrantAccountId = n.GetStringValue(); } },
                { "grantOfferId", n => { GrantOfferId = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "status", n => { Status = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1Status>(global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1Status.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1Balance>("balances", Balances);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1GrantCounterparty>("counterparty", Counterparty);
            writer.WriteStringValue("grantAccountId", GrantAccountId);
            writer.WriteStringValue("grantOfferId", GrantOfferId);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CapitalServiceV1Status>("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
