// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CardDetails : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The sequence number for the debit. For example, send **2** if this is the second debit for the subscription. The sequence number is included in the notification sent to the shopper.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BillingSequenceNumber { get; set; }
#nullable restore
#else
        public string BillingSequenceNumber { get; set; }
#endif
        /// <summary>&quot;Secondary brand of the card. For example: **plastix**, **hmclub**.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Brand { get; set; }
#nullable restore
#else
        public string Brand { get; set; }
#endif
        /// <summary>The checkout attempt identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CheckoutAttemptId { get; set; }
#nullable restore
#else
        public string CheckoutAttemptId { get; set; }
#endif
        /// <summary>The cupsecureplusSmscode property</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CupsecureplusSmscode { get; set; }
#nullable restore
#else
        public string CupsecureplusSmscode { get; set; }
#endif
        /// <summary>The card verification code. Only collect raw card data if you are [fully PCI compliant](https://docs.adyen.com/development-resources/pci-dss-compliance-guide).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Cvc { get; set; }
#nullable restore
#else
        public string Cvc { get; set; }
#endif
        /// <summary>Only include this for JSON Web Encryption (JWE) implementations. The JWE-encrypted card details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EncryptedCard { get; set; }
#nullable restore
#else
        public string EncryptedCard { get; set; }
#endif
        /// <summary>The encrypted card number.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EncryptedCardNumber { get; set; }
#nullable restore
#else
        public string EncryptedCardNumber { get; set; }
#endif
        /// <summary>The encrypted card expiry month.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EncryptedExpiryMonth { get; set; }
#nullable restore
#else
        public string EncryptedExpiryMonth { get; set; }
#endif
        /// <summary>The encrypted card expiry year.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EncryptedExpiryYear { get; set; }
#nullable restore
#else
        public string EncryptedExpiryYear { get; set; }
#endif
        /// <summary>This field contains an encrypted, one-time password or an authentication code provided by the cardholder.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EncryptedPassword { get; set; }
#nullable restore
#else
        public string EncryptedPassword { get; set; }
#endif
        /// <summary>The encrypted card verification code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EncryptedSecurityCode { get; set; }
#nullable restore
#else
        public string EncryptedSecurityCode { get; set; }
#endif
        /// <summary>The card expiry month. Only collect raw card data if you are [fully PCI compliant](https://docs.adyen.com/development-resources/pci-dss-compliance-guide).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExpiryMonth { get; set; }
#nullable restore
#else
        public string ExpiryMonth { get; set; }
#endif
        /// <summary>The card expiry year. Only collect raw card data if you are [fully PCI compliant](https://docs.adyen.com/development-resources/pci-dss-compliance-guide).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExpiryYear { get; set; }
#nullable restore
#else
        public string ExpiryYear { get; set; }
#endif
        /// <summary>The encoded fastlane data blob</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FastlaneData { get; set; }
#nullable restore
#else
        public string FastlaneData { get; set; }
#endif
        /// <summary>The funding source that should be used when multiple sources are available. For Brazilian combo cards, by default the funding source is credit. To use debit, set this value to **debit**.</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.CardDetails_fundingSource? FundingSource { get; set; }
        /// <summary>The name of the card holder.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HolderName { get; set; }
#nullable restore
#else
        public string HolderName { get; set; }
#endif
        /// <summary>The transaction identifier from card schemes. This is the [`networkTxReference`](https://docs.adyen.com/api-explorer/Checkout/latest/post/payments#responses-200-additionalData-ResponseAdditionalDataCommon-networkTxReference) from the response to the first payment.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NetworkPaymentReference { get; set; }
#nullable restore
#else
        public string NetworkPaymentReference { get; set; }
#endif
        /// <summary>The card number. Only collect raw card data if you are [fully PCI compliant](https://docs.adyen.com/development-resources/pci-dss-compliance-guide).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Number { get; set; }
#nullable restore
#else
        public string Number { get; set; }
#endif
        /// <summary>This is the `recurringDetailReference` returned in the response when you created the token.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecurringDetailReference { get; set; }
#nullable restore
#else
        public string RecurringDetailReference { get; set; }
#endif
        /// <summary>Base64-encoded JSON object containing SDK related parameters required by the SDK</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SdkData { get; set; }
#nullable restore
#else
        public string SdkData { get; set; }
#endif
        /// <summary>The `shopperNotificationReference` returned in the response when you requested to notify the shopper. Used only for recurring payments in India.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShopperNotificationReference { get; set; }
#nullable restore
#else
        public string ShopperNotificationReference { get; set; }
#endif
        /// <summary>An identifier used for the Click to Pay transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SrcCorrelationId { get; set; }
#nullable restore
#else
        public string SrcCorrelationId { get; set; }
#endif
        /// <summary>The SRC reference for the Click to Pay token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SrcDigitalCardId { get; set; }
#nullable restore
#else
        public string SrcDigitalCardId { get; set; }
#endif
        /// <summary>The scheme that is being used for Click to Pay.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SrcScheme { get; set; }
#nullable restore
#else
        public string SrcScheme { get; set; }
#endif
        /// <summary>The reference for the Click to Pay token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SrcTokenReference { get; set; }
#nullable restore
#else
        public string SrcTokenReference { get; set; }
#endif
        /// <summary>This is the `recurringDetailReference` returned in the response when you created the token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StoredPaymentMethodId { get; set; }
#nullable restore
#else
        public string StoredPaymentMethodId { get; set; }
#endif
        /// <summary>Required for mobile integrations. Version of the 3D Secure 2 mobile SDK.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ThreeDS2SdkVersion { get; set; }
#nullable restore
#else
        public string ThreeDS2SdkVersion { get; set; }
#endif
        /// <summary>Default payment method details. Common for scheme payment methods, and for simple payment method details.</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.CardDetails_type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.CardDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.CardDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.CardDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "billingSequenceNumber", n => { BillingSequenceNumber = n.GetStringValue(); } },
                { "brand", n => { Brand = n.GetStringValue(); } },
                { "checkoutAttemptId", n => { CheckoutAttemptId = n.GetStringValue(); } },
                { "cupsecureplus.smscode", n => { CupsecureplusSmscode = n.GetStringValue(); } },
                { "cvc", n => { Cvc = n.GetStringValue(); } },
                { "encryptedCard", n => { EncryptedCard = n.GetStringValue(); } },
                { "encryptedCardNumber", n => { EncryptedCardNumber = n.GetStringValue(); } },
                { "encryptedExpiryMonth", n => { EncryptedExpiryMonth = n.GetStringValue(); } },
                { "encryptedExpiryYear", n => { EncryptedExpiryYear = n.GetStringValue(); } },
                { "encryptedPassword", n => { EncryptedPassword = n.GetStringValue(); } },
                { "encryptedSecurityCode", n => { EncryptedSecurityCode = n.GetStringValue(); } },
                { "expiryMonth", n => { ExpiryMonth = n.GetStringValue(); } },
                { "expiryYear", n => { ExpiryYear = n.GetStringValue(); } },
                { "fastlaneData", n => { FastlaneData = n.GetStringValue(); } },
                { "fundingSource", n => { FundingSource = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.CardDetails_fundingSource>(); } },
                { "holderName", n => { HolderName = n.GetStringValue(); } },
                { "networkPaymentReference", n => { NetworkPaymentReference = n.GetStringValue(); } },
                { "number", n => { Number = n.GetStringValue(); } },
                { "recurringDetailReference", n => { RecurringDetailReference = n.GetStringValue(); } },
                { "sdkData", n => { SdkData = n.GetStringValue(); } },
                { "shopperNotificationReference", n => { ShopperNotificationReference = n.GetStringValue(); } },
                { "srcCorrelationId", n => { SrcCorrelationId = n.GetStringValue(); } },
                { "srcDigitalCardId", n => { SrcDigitalCardId = n.GetStringValue(); } },
                { "srcScheme", n => { SrcScheme = n.GetStringValue(); } },
                { "srcTokenReference", n => { SrcTokenReference = n.GetStringValue(); } },
                { "storedPaymentMethodId", n => { StoredPaymentMethodId = n.GetStringValue(); } },
                { "threeDS2SdkVersion", n => { ThreeDS2SdkVersion = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.CardDetails_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("billingSequenceNumber", BillingSequenceNumber);
            writer.WriteStringValue("brand", Brand);
            writer.WriteStringValue("checkoutAttemptId", CheckoutAttemptId);
            writer.WriteStringValue("cupsecureplus.smscode", CupsecureplusSmscode);
            writer.WriteStringValue("cvc", Cvc);
            writer.WriteStringValue("encryptedCard", EncryptedCard);
            writer.WriteStringValue("encryptedCardNumber", EncryptedCardNumber);
            writer.WriteStringValue("encryptedExpiryMonth", EncryptedExpiryMonth);
            writer.WriteStringValue("encryptedExpiryYear", EncryptedExpiryYear);
            writer.WriteStringValue("encryptedPassword", EncryptedPassword);
            writer.WriteStringValue("encryptedSecurityCode", EncryptedSecurityCode);
            writer.WriteStringValue("expiryMonth", ExpiryMonth);
            writer.WriteStringValue("expiryYear", ExpiryYear);
            writer.WriteStringValue("fastlaneData", FastlaneData);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.CardDetails_fundingSource>("fundingSource", FundingSource);
            writer.WriteStringValue("holderName", HolderName);
            writer.WriteStringValue("networkPaymentReference", NetworkPaymentReference);
            writer.WriteStringValue("number", Number);
            writer.WriteStringValue("recurringDetailReference", RecurringDetailReference);
            writer.WriteStringValue("sdkData", SdkData);
            writer.WriteStringValue("shopperNotificationReference", ShopperNotificationReference);
            writer.WriteStringValue("srcCorrelationId", SrcCorrelationId);
            writer.WriteStringValue("srcDigitalCardId", SrcDigitalCardId);
            writer.WriteStringValue("srcScheme", SrcScheme);
            writer.WriteStringValue("srcTokenReference", SrcTokenReference);
            writer.WriteStringValue("storedPaymentMethodId", StoredPaymentMethodId);
            writer.WriteStringValue("threeDS2SdkVersion", ThreeDS2SdkVersion);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.CardDetails_type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
