// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CarRental : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The customer service phone number of the car rental company.* Format: Alphanumeric* maxLength: 17* For US and CA numbers must be 10 characters in length* Must not contain any special characters such as + or -* Must not start with a space or be all spaces.* Must not be all zeros.* **additionalData key:** `carRental.customerServiceTollFreeNumber`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CustomerServicePhoneNumber { get; set; }
#nullable restore
#else
        public string CustomerServicePhoneNumber { get; set; }
#endif
        /// <summary>Indicates if the customer didn&apos;t pick up their rental car.* **additionalData key:** `carRental.noShowIndicator`</summary>
        public bool? NoShow { get; set; }
        /// <summary>The pickupInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PickupInfo? PickupInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PickupInfo PickupInfo { get; set; }
#endif
        /// <summary>Indicates whether the rental rate is daily or weekly.* **additionalData key:** `carRental.rateIndicator`</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.CarRentalRateType? RateType { get; set; }
        /// <summary>The rental agreement number for the car rental.* Format: ASCII* maxLength: 9 characters* Must not start with a space or be all spaces.* Must not be all zeros.* **additionalData key:** `carRental.rentalAgreementNumber`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RentalAgreementNumber { get; set; }
#nullable restore
#else
        public string RentalAgreementNumber { get; set; }
#endif
        /// <summary>The classification of the rental car.* Format: Alphanumeric* maxLength: 4 characters* Must not start with a space or be all spaces.* Must not be all zeros.* **additionalData key:** `carRental.rentalClassId`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RentalClassId { get; set; }
#nullable restore
#else
        public string RentalClassId { get; set; }
#endif
        /// <summary>The number of days the car is rented for.* Format: Numeric* Max value: 9999* **additionalData key:** `carRental.daysRented`</summary>
        public int? RentalDays { get; set; }
        /// <summary>Rental rate, in [minor units](https://docs.adyen.com/development-resources/currency-codes).* For example, 2000 means USD 20.00.* Encoding: Numeric* Max value: 10000000000* Frequency of the rental rate is specified in the rateType field.* **additionalData key:** `carRental.rate`</summary>
        public long? RentalRate { get; set; }
        /// <summary>The rentalSurcharges property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.RentalSurcharges? RentalSurcharges { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.RentalSurcharges RentalSurcharges { get; set; }
#endif
        /// <summary>The name of the person renting the car.* Format: ASCII* Must not start with a space or be all spaces.* Must not be all zeros.* **additionalData key:** `carRental.renterName`</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RenterName { get; set; }
#nullable restore
#else
        public string RenterName { get; set; }
#endif
        /// <summary>The returnInfo property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.ReturnInfo? ReturnInfo { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.ReturnInfo ReturnInfo { get; set; }
#endif
        /// <summary>Indicates if the goods or services were tax-exempt, or if tax was not collected.* **additionalData key:** `carRental.taxExemptIndicator`</summary>
        public bool? TaxExempt { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.CarRental"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.CarRental CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.CarRental();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "customerServicePhoneNumber", n => { CustomerServicePhoneNumber = n.GetStringValue(); } },
                { "noShow", n => { NoShow = n.GetBoolValue(); } },
                { "pickupInfo", n => { PickupInfo = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PickupInfo>(global::Soenneker.Adyen.OpenApiClient.Models.PickupInfo.CreateFromDiscriminatorValue); } },
                { "rateType", n => { RateType = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.CarRentalRateType>(); } },
                { "rentalAgreementNumber", n => { RentalAgreementNumber = n.GetStringValue(); } },
                { "rentalClassId", n => { RentalClassId = n.GetStringValue(); } },
                { "rentalDays", n => { RentalDays = n.GetIntValue(); } },
                { "rentalRate", n => { RentalRate = n.GetLongValue(); } },
                { "rentalSurcharges", n => { RentalSurcharges = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.RentalSurcharges>(global::Soenneker.Adyen.OpenApiClient.Models.RentalSurcharges.CreateFromDiscriminatorValue); } },
                { "renterName", n => { RenterName = n.GetStringValue(); } },
                { "returnInfo", n => { ReturnInfo = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.ReturnInfo>(global::Soenneker.Adyen.OpenApiClient.Models.ReturnInfo.CreateFromDiscriminatorValue); } },
                { "taxExempt", n => { TaxExempt = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("customerServicePhoneNumber", CustomerServicePhoneNumber);
            writer.WriteBoolValue("noShow", NoShow);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PickupInfo>("pickupInfo", PickupInfo);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.CarRentalRateType>("rateType", RateType);
            writer.WriteStringValue("rentalAgreementNumber", RentalAgreementNumber);
            writer.WriteStringValue("rentalClassId", RentalClassId);
            writer.WriteIntValue("rentalDays", RentalDays);
            writer.WriteLongValue("rentalRate", RentalRate);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.RentalSurcharges>("rentalSurcharges", RentalSurcharges);
            writer.WriteStringValue("renterName", RenterName);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.ReturnInfo>("returnInfo", ReturnInfo);
            writer.WriteBoolValue("taxExempt", TaxExempt);
        }
    }
}
#pragma warning restore CS0618
