// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CostEstimateAssumptions : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>If true, the cardholder is expected to successfully authorise via 3D Secure.</summary>
        public bool? Assume3DSecureAuthenticated { get; set; }
        /// <summary>If true, the transaction is expected to have valid Level 3 data.</summary>
        public bool? AssumeLevel3Data { get; set; }
        /// <summary>If not zero, the number of installments.</summary>
        public int? Installments { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.CostEstimateAssumptions"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.CostEstimateAssumptions CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.CostEstimateAssumptions();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "assume3DSecureAuthenticated", n => { Assume3DSecureAuthenticated = n.GetBoolValue(); } },
                { "assumeLevel3Data", n => { AssumeLevel3Data = n.GetBoolValue(); } },
                { "installments", n => { Installments = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("assume3DSecureAuthenticated", Assume3DSecureAuthenticated);
            writer.WriteBoolValue("assumeLevel3Data", AssumeLevel3Data);
            writer.WriteIntValue("installments", Installments);
        }
    }
}
#pragma warning restore CS0618
