// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CreatePermitRequest : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The merchant account identifier, with which you want to process the transaction.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MerchantAccount { get; set; }
#nullable restore
#else
        public string MerchantAccount { get; set; }
#endif
        /// <summary>The permits to create for this recurring contract.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Adyen.OpenApiClient.Models.Permit>? Permits { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Adyen.OpenApiClient.Models.Permit> Permits { get; set; }
#endif
        /// <summary>The recurring contract the new permits will use.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecurringDetailReference { get; set; }
#nullable restore
#else
        public string RecurringDetailReference { get; set; }
#endif
        /// <summary>The shopper&apos;s reference to uniquely identify this shopper (e.g. user ID or account ID).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShopperReference { get; set; }
#nullable restore
#else
        public string ShopperReference { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.CreatePermitRequest"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.CreatePermitRequest CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.CreatePermitRequest();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "merchantAccount", n => { MerchantAccount = n.GetStringValue(); } },
                { "permits", n => { Permits = n.GetCollectionOfObjectValues<global::Soenneker.Adyen.OpenApiClient.Models.Permit>(global::Soenneker.Adyen.OpenApiClient.Models.Permit.CreateFromDiscriminatorValue)?.AsList(); } },
                { "recurringDetailReference", n => { RecurringDetailReference = n.GetStringValue(); } },
                { "shopperReference", n => { ShopperReference = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("merchantAccount", MerchantAccount);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Adyen.OpenApiClient.Models.Permit>("permits", Permits);
            writer.WriteStringValue("recurringDetailReference", RecurringDetailReference);
            writer.WriteStringValue("shopperReference", ShopperReference);
        }
    }
}
#pragma warning restore CS0618
