// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>&quot;Specifies how payment methods should be filtered based on the &apos;store&apos; parameter:  - &apos;exclusive&apos;: Only payment methods belonging to the specified &apos;store&apos; are returned.  - &apos;inclusive&apos;: Payment methods from the &apos;store&apos; and those not associated with any other store are returned.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum CreateCheckoutSessionRequest_storeFiltrationMode
    {
        [EnumMember(Value = "exclusive")]
        #pragma warning disable CS1591
        Exclusive,
        #pragma warning restore CS1591
        [EnumMember(Value = "inclusive")]
        #pragma warning disable CS1591
        Inclusive,
        #pragma warning restore CS1591
        [EnumMember(Value = "skipFilter")]
        #pragma warning disable CS1591
        SkipFilter,
        #pragma warning restore CS1591
    }
}
