// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>
    /// Information related to a currency conversion.A currency conversion occurred in the payment, and the merchant needs to know information related to this conversion (e.g. to print on the sale receipt).
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CurrencyConversion : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Commission for a currency conversion.</summary>
        public double? Commission { get; set; }
        /// <summary>The ConvertedAmount property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.ConvertedAmount? ConvertedAmount { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.ConvertedAmount ConvertedAmount { get; set; }
#endif
        /// <summary>Notify if the customer has approved something. Indicates if the customer has accepted a currency conversion.</summary>
        public bool? CustomerApprovedFlag { get; set; }
        /// <summary>Declaration to present to the customer or the cashier for validation.If a declaration has to be presented to the customer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Declaration { get; set; }
#nullable restore
#else
        public string Declaration { get; set; }
#endif
        /// <summary>Markup of a currency conversion amount as a percentage.</summary>
        public double? Markup { get; set; }
        /// <summary>Rate of currency conversion.</summary>
        public double? Rate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.Models.CurrencyConversion"/> and sets the default values.
        /// </summary>
        public CurrencyConversion()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.CurrencyConversion"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.CurrencyConversion CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.CurrencyConversion();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "Commission", n => { Commission = n.GetDoubleValue(); } },
                { "ConvertedAmount", n => { ConvertedAmount = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.ConvertedAmount>(global::Soenneker.Adyen.OpenApiClient.Models.ConvertedAmount.CreateFromDiscriminatorValue); } },
                { "CustomerApprovedFlag", n => { CustomerApprovedFlag = n.GetBoolValue(); } },
                { "Declaration", n => { Declaration = n.GetStringValue(); } },
                { "Markup", n => { Markup = n.GetDoubleValue(); } },
                { "Rate", n => { Rate = n.GetDoubleValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteDoubleValue("Commission", Commission);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.ConvertedAmount>("ConvertedAmount", ConvertedAmount);
            writer.WriteBoolValue("CustomerApprovedFlag", CustomerApprovedFlag);
            writer.WriteStringValue("Declaration", Declaration);
            writer.WriteDoubleValue("Markup", Markup);
            writer.WriteDoubleValue("Rate", Rate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
