// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CustomNotification : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The amount property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3Amount? Amount { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3Amount Amount { get; set; }
#endif
        /// <summary>The event that caused the notification to be sent.Currently supported values:* **AUTHORISATION*** **CANCELLATION*** **REFUND*** **CAPTURE*** **REPORT_AVAILABLE*** **CHARGEBACK*** **REQUEST_FOR_INFORMATION*** **NOTIFICATION_OF_CHARGEBACK*** **NOTIFICATIONTEST*** **ORDER_OPENED*** **ORDER_CLOSED*** **CHARGEBACK_REVERSED*** **REFUNDED_REVERSED*** **REFUND_WITH_DATA**</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EventCode { get; set; }
#nullable restore
#else
        public string EventCode { get; set; }
#endif
        /// <summary>&quot;The time of the event. Format: [ISO 8601](http://www.w3.org/TR/NOTE-datetime), YYYY-MM-DDThh:mm:ssTZD.&quot;</summary>
        public DateTimeOffset? EventDate { get; set; }
        /// <summary>Your reference for the custom test notification.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MerchantReference { get; set; }
#nullable restore
#else
        public string MerchantReference { get; set; }
#endif
        /// <summary>The payment method for the payment that the notification is about. Possible values:* **amex*** **visa*** **mc*** **maestro*** **bcmc*** **paypal** * **sms** * **bankTransfer_NL*** **bankTransfer_DE*** **bankTransfer_BE*** **ideal*** **elv*** **sepadirectdebit**</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PaymentMethod { get; set; }
#nullable restore
#else
        public string PaymentMethod { get; set; }
#endif
        /// <summary>A description of what caused the notification.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reason { get; set; }
#nullable restore
#else
        public string Reason { get; set; }
#endif
        /// <summary>The outcome of the event which the notification is about. Set to either **true** or **false**. </summary>
        public bool? Success { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.CustomNotification"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.CustomNotification CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.CustomNotification();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amount", n => { Amount = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3Amount>(global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3Amount.CreateFromDiscriminatorValue); } },
                { "eventCode", n => { EventCode = n.GetStringValue(); } },
                { "eventDate", n => { EventDate = n.GetDateTimeOffsetValue(); } },
                { "merchantReference", n => { MerchantReference = n.GetStringValue(); } },
                { "paymentMethod", n => { PaymentMethod = n.GetStringValue(); } },
                { "reason", n => { Reason = n.GetStringValue(); } },
                { "success", n => { Success = n.GetBoolValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3Amount>("amount", Amount);
            writer.WriteStringValue("eventCode", EventCode);
            writer.WriteDateTimeOffsetValue("eventDate", EventDate);
            writer.WriteStringValue("merchantReference", MerchantReference);
            writer.WriteStringValue("paymentMethod", PaymentMethod);
            writer.WriteStringValue("reason", Reason);
            writer.WriteBoolValue("success", Success);
        }
    }
}
#pragma warning restore CS0618
