// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DebitAccountHolderResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The code of the account holder.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountHolderCode { get; set; }
#nullable restore
#else
        public string AccountHolderCode { get; set; }
#endif
        /// <summary>The Adyen-generated unique alphanumeric identifier (UUID) of the account holder&apos;s bank account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankAccountUUID { get; set; }
#nullable restore
#else
        public string BankAccountUUID { get; set; }
#endif
        /// <summary>Contains field validation errors that would prevent requests from being processed.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Adyen.OpenApiClient.Models.FundServiceV6ErrorFieldType>? InvalidFields { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Adyen.OpenApiClient.Models.FundServiceV6ErrorFieldType> InvalidFields { get; set; }
#endif
        /// <summary>List of the `reference` values from the `split` array in the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? MerchantReferences { get; set; }
#nullable restore
#else
        public List<string> MerchantReferences { get; set; }
#endif
        /// <summary>The reference of a request. Can be used to uniquely identify the request.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PspReference { get; set; }
#nullable restore
#else
        public string PspReference { get; set; }
#endif
        /// <summary>The result code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ResultCode { get; set; }
#nullable restore
#else
        public string ResultCode { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.DebitAccountHolderResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.DebitAccountHolderResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.DebitAccountHolderResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountHolderCode", n => { AccountHolderCode = n.GetStringValue(); } },
                { "bankAccountUUID", n => { BankAccountUUID = n.GetStringValue(); } },
                { "invalidFields", n => { InvalidFields = n.GetCollectionOfObjectValues<global::Soenneker.Adyen.OpenApiClient.Models.FundServiceV6ErrorFieldType>(global::Soenneker.Adyen.OpenApiClient.Models.FundServiceV6ErrorFieldType.CreateFromDiscriminatorValue)?.AsList(); } },
                { "merchantReferences", n => { MerchantReferences = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "pspReference", n => { PspReference = n.GetStringValue(); } },
                { "resultCode", n => { ResultCode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountHolderCode", AccountHolderCode);
            writer.WriteStringValue("bankAccountUUID", BankAccountUUID);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Adyen.OpenApiClient.Models.FundServiceV6ErrorFieldType>("invalidFields", InvalidFields);
            writer.WriteCollectionOfPrimitiveValues<string>("merchantReferences", MerchantReferences);
            writer.WriteStringValue("pspReference", PspReference);
            writer.WriteStringValue("resultCode", ResultCode);
        }
    }
}
#pragma warning restore CS0618
