// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DocumentDetail : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The code of account holder, to which the document applies.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AccountHolderCode { get; set; }
#nullable restore
#else
        public string AccountHolderCode { get; set; }
#endif
        /// <summary>The Adyen-generated [`bankAccountUUID`](https://docs.adyen.com/api-explorer/#/Account/latest/post/createAccountHolder__resParam_accountHolderDetails-bankAccountDetails-bankAccountUUID) to which the document must be linked. Refer to [Bank account check](https://docs.adyen.com/classic-platforms/verification-checks/bank-account-check#uploading-a-bank-statement) for details on when a document should be submitted.&gt;Required if the `documentType` is **BANK_STATEMENT**, where a document is being submitted in order to verify a bank account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankAccountUUID { get; set; }
#nullable restore
#else
        public string BankAccountUUID { get; set; }
#endif
        /// <summary>Description of the document.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>&quot;The type of the document. Refer to [Verification checks](https://docs.adyen.com/classic-platforms/verification-checks) for details on when each document type should be submitted and for the accepted file formats.Permitted values:* **BANK_STATEMENT**: A file containing a bank statement or other document proving ownership of a specific bank account.* **COMPANY_REGISTRATION_SCREENING** (Supported from v5 and later): A file containing a company registration document.* **CONSTITUTIONAL_DOCUMENT**: A file containing information about the account holder&apos;s legal arrangement.* **PASSPORT**: A file containing the identity page(s) of a passport.* **ID_CARD_FRONT**: A file containing only the front of the ID card. In order for a document to be usable, both the **ID_CARD_FRONT** and **ID_CARD_BACK** must be submitted.* **ID_CARD_BACK**: A file containing only the back of the ID card. In order for a document to be usable, both the **ID_CARD_FRONT** and **ID_CARD_BACK** must be submitted.* **DRIVING_LICENCE_FRONT**: A file containing only the front of the driving licence. In order for a document to be usable, both the **DRIVING_LICENCE_FRONT** and **DRIVING_LICENCE_BACK** must be submitted.* **DRIVING_LICENCE_BACK**: A file containing only the back of the driving licence. In order for a document to be usable, both the **DRIVING_LICENCE_FRONT** and **DRIVING_LICENCE_FRONT** must be submitted.&quot;</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.DocumentDetail_documentType? DocumentType { get; set; }
        /// <summary>Filename of the document.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Filename { get; set; }
#nullable restore
#else
        public string Filename { get; set; }
#endif
        /// <summary>The Adyen-generated [`legalArrangementCode`](https://docs.adyen.com/api-explorer/#/Account/latest/post/createAccountHolder__resParam_accountHolderDetails-legalArrangements-legalArrangementCode) to which the document must be linked.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LegalArrangementCode { get; set; }
#nullable restore
#else
        public string LegalArrangementCode { get; set; }
#endif
        /// <summary>The Adyen-generated [`legalArrangementEntityCode`](https://docs.adyen.com/api-explorer/#/Account/v6/post/createAccountHolder__resParam_accountHolderDetails-legalArrangements-legalArrangementEntities-legalArrangementEntityCode)  to which the document must be linked.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LegalArrangementEntityCode { get; set; }
#nullable restore
#else
        public string LegalArrangementEntityCode { get; set; }
#endif
        /// <summary>The Adyen-generated [`shareholderCode`](https://docs.adyen.com/api-explorer/#/Account/latest/post/createAccountHolder__resParam_accountHolderDetails-businessDetails-shareholders-shareholderCode) to which the document must be linked. Refer to [Verification checks](https://docs.adyen.com/classic-platforms/verification-checks) for details on when a document should be submitted.&gt;Required if the account holder has a `legalEntity` of type **Business** and the `documentType` is either **PASSPORT**, **ID_CARD_FRONT**, **ID_CARD_BACK**, **DRIVING_LICENCE_FRONT**, or **DRIVING_LICENCE_BACK**. </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShareholderCode { get; set; }
#nullable restore
#else
        public string ShareholderCode { get; set; }
#endif
        /// <summary>The Adyen-generated [`signatoryCode`](https://docs.adyen.com/api-explorer/#/Account/v6/post/createAccountHolder__resParam_accountHolderDetails-businessDetails-signatories-signatoryCode) to which the document must be linked.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SignatoryCode { get; set; }
#nullable restore
#else
        public string SignatoryCode { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.DocumentDetail"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.DocumentDetail CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.DocumentDetail();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountHolderCode", n => { AccountHolderCode = n.GetStringValue(); } },
                { "bankAccountUUID", n => { BankAccountUUID = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "documentType", n => { DocumentType = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.DocumentDetail_documentType>(); } },
                { "filename", n => { Filename = n.GetStringValue(); } },
                { "legalArrangementCode", n => { LegalArrangementCode = n.GetStringValue(); } },
                { "legalArrangementEntityCode", n => { LegalArrangementEntityCode = n.GetStringValue(); } },
                { "shareholderCode", n => { ShareholderCode = n.GetStringValue(); } },
                { "signatoryCode", n => { SignatoryCode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("accountHolderCode", AccountHolderCode);
            writer.WriteStringValue("bankAccountUUID", BankAccountUUID);
            writer.WriteStringValue("description", Description);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.DocumentDetail_documentType>("documentType", DocumentType);
            writer.WriteStringValue("filename", Filename);
            writer.WriteStringValue("legalArrangementCode", LegalArrangementCode);
            writer.WriteStringValue("legalArrangementEntityCode", LegalArrangementEntityCode);
            writer.WriteStringValue("shareholderCode", ShareholderCode);
            writer.WriteStringValue("signatoryCode", SignatoryCode);
        }
    }
}
#pragma warning restore CS0618
