// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class EftDetails : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The bank account number (without separators).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankAccountNumber { get; set; }
#nullable restore
#else
        public string BankAccountNumber { get; set; }
#endif
        /// <summary>The financial institution code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankCode { get; set; }
#nullable restore
#else
        public string BankCode { get; set; }
#endif
        /// <summary>The bank routing number of the account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BankLocationId { get; set; }
#nullable restore
#else
        public string BankLocationId { get; set; }
#endif
        /// <summary>The checkout attempt identifier.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CheckoutAttemptId { get; set; }
#nullable restore
#else
        public string CheckoutAttemptId { get; set; }
#endif
        /// <summary>&quot;The name of the bank account holder.If you submit a name with non-Latin characters, we automatically replace some of them with corresponding Latin characters to meet the FATF recommendations. For example:* χ12 is converted to ch12.* üA is converted to euA.* Peter Møller is converted to Peter Mller, because banks don&apos;t accept &apos;ø&apos;.After replacement, the ownerName must have at least three alphanumeric characters (A-Z, a-z, 0-9), and at least one of them must be a valid Latin character (A-Z, a-z). For example:* John17 - allowed.* J17 - allowed.* 171 - not allowed.* John-7 - allowed.&gt; If provided details don&apos;t match the required format, the response returns the error message: 203 &apos;Invalid bank account holder name&apos;.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerName { get; set; }
#nullable restore
#else
        public string OwnerName { get; set; }
#endif
        /// <summary>This is the `recurringDetailReference` returned in the response when you created the token.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RecurringDetailReference { get; set; }
#nullable restore
#else
        public string RecurringDetailReference { get; set; }
#endif
        /// <summary>Base64-encoded JSON object containing SDK related parameters required by the SDK</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? SdkData { get; set; }
#nullable restore
#else
        public string SdkData { get; set; }
#endif
        /// <summary>This is the `recurringDetailReference` returned in the response when you created the token.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StoredPaymentMethodId { get; set; }
#nullable restore
#else
        public string StoredPaymentMethodId { get; set; }
#endif
        /// <summary>**eft**</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.EftDetails_type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.EftDetails"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.EftDetails CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.EftDetails();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "bankAccountNumber", n => { BankAccountNumber = n.GetStringValue(); } },
                { "bankCode", n => { BankCode = n.GetStringValue(); } },
                { "bankLocationId", n => { BankLocationId = n.GetStringValue(); } },
                { "checkoutAttemptId", n => { CheckoutAttemptId = n.GetStringValue(); } },
                { "ownerName", n => { OwnerName = n.GetStringValue(); } },
                { "recurringDetailReference", n => { RecurringDetailReference = n.GetStringValue(); } },
                { "sdkData", n => { SdkData = n.GetStringValue(); } },
                { "storedPaymentMethodId", n => { StoredPaymentMethodId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.EftDetails_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("bankAccountNumber", BankAccountNumber);
            writer.WriteStringValue("bankCode", BankCode);
            writer.WriteStringValue("bankLocationId", BankLocationId);
            writer.WriteStringValue("checkoutAttemptId", CheckoutAttemptId);
            writer.WriteStringValue("ownerName", OwnerName);
            writer.WriteStringValue("recurringDetailReference", RecurringDetailReference);
            writer.WriteStringValue("sdkData", SdkData);
            writer.WriteStringValue("storedPaymentMethodId", StoredPaymentMethodId);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.EftDetails_type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
