// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GeneratePciDescriptionRequest_additionalSalesChannels
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "eCommerce")]
        #pragma warning disable CS1591
        ECommerce,
        #pragma warning restore CS1591
        [EnumMember(Value = "ecomMoto")]
        #pragma warning disable CS1591
        EcomMoto,
        #pragma warning restore CS1591
        [EnumMember(Value = "pos")]
        #pragma warning disable CS1591
        Pos,
        #pragma warning restore CS1591
        [EnumMember(Value = "posMoto")]
        #pragma warning disable CS1591
        PosMoto,
        #pragma warning restore CS1591
    }
}
