// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class GetTermsOfServiceDocumentResponse : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The Terms of Service document in Base64-encoded format.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public byte[]? Document { get; set; }
#nullable restore
#else
        public byte[] Document { get; set; }
#endif
        /// <summary>The unique identifier of the legal entity.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>&quot;The language used for the Terms of Service document, specified by the two-letter [ISO 639-1](https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes) language code. Possible value: **en** for English or **fr** for French.Note that French is only available for some integration types in certain countries/regions. Reach out to your Adyen contact for more information.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Language { get; set; }
#nullable restore
#else
        public string Language { get; set; }
#endif
        /// <summary>The format of the Terms of Service document.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TermsOfServiceDocumentFormat { get; set; }
#nullable restore
#else
        public string TermsOfServiceDocumentFormat { get; set; }
#endif
        /// <summary>The unique identifier of the Terms of Service document.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TermsOfServiceDocumentId { get; set; }
#nullable restore
#else
        public string TermsOfServiceDocumentId { get; set; }
#endif
        /// <summary>The type of Terms of Service.Possible values:*  **adyenForPlatformsManage***  **adyenIssuing***  **adyenForPlatformsAdvanced***  **adyenCapital***  **adyenAccount***  **adyenCard***  **adyenFranchisee***  **adyenPccr***  **adyenChargeCard***  **kycOnInvite**</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.GetTermsOfServiceDocumentResponse_type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.GetTermsOfServiceDocumentResponse"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.GetTermsOfServiceDocumentResponse CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.GetTermsOfServiceDocumentResponse();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "document", n => { Document = n.GetByteArrayValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "language", n => { Language = n.GetStringValue(); } },
                { "termsOfServiceDocumentFormat", n => { TermsOfServiceDocumentFormat = n.GetStringValue(); } },
                { "termsOfServiceDocumentId", n => { TermsOfServiceDocumentId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.GetTermsOfServiceDocumentResponse_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteByteArrayValue("document", Document);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("language", Language);
            writer.WriteStringValue("termsOfServiceDocumentFormat", TermsOfServiceDocumentFormat);
            writer.WriteStringValue("termsOfServiceDocumentId", TermsOfServiceDocumentId);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.GetTermsOfServiceDocumentResponse_type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
