// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class LineItem : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Item amount excluding the tax, in [minor units](https://docs.adyen.com/development-resources/currency-codes/#minor-units).</summary>
        public long? AmountExcludingTax { get; set; }
        /// <summary>Item amount including the tax, in [minor units](https://docs.adyen.com/development-resources/currency-codes/#minor-units).</summary>
        public long? AmountIncludingTax { get; set; }
        /// <summary>Brand of the item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Brand { get; set; }
#nullable restore
#else
        public string Brand { get; set; }
#endif
        /// <summary>Color of the item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Color { get; set; }
#nullable restore
#else
        public string Color { get; set; }
#endif
        /// <summary>Description of the line item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>ID of the line item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>Link to the picture of the purchased item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ImageUrl { get; set; }
#nullable restore
#else
        public string ImageUrl { get; set; }
#endif
        /// <summary>Item category, used by the payment methods PayPal and Ratepay.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ItemCategory { get; set; }
#nullable restore
#else
        public string ItemCategory { get; set; }
#endif
        /// <summary>Manufacturer of the item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Manufacturer { get; set; }
#nullable restore
#else
        public string Manufacturer { get; set; }
#endif
        /// <summary>Marketplace seller id.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MarketplaceSellerId { get; set; }
#nullable restore
#else
        public string MarketplaceSellerId { get; set; }
#endif
        /// <summary>Link to the purchased item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ProductUrl { get; set; }
#nullable restore
#else
        public string ProductUrl { get; set; }
#endif
        /// <summary>Number of items.</summary>
        public long? Quantity { get; set; }
        /// <summary>Email associated with the given product in the basket (usually in electronic gift cards).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReceiverEmail { get; set; }
#nullable restore
#else
        public string ReceiverEmail { get; set; }
#endif
        /// <summary>Size of the item.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Size { get; set; }
#nullable restore
#else
        public string Size { get; set; }
#endif
        /// <summary>Stock keeping unit.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Sku { get; set; }
#nullable restore
#else
        public string Sku { get; set; }
#endif
        /// <summary>Tax amount, in [minor units](https://docs.adyen.com/development-resources/currency-codes/#minor-units).</summary>
        public long? TaxAmount { get; set; }
        /// <summary>Tax percentage, represented as a [basis point](https://en.wikipedia.org/wiki/Basis_point) integer. For example: - **530** for 5.3% (five point three percent)  - **2100** for 21% (twenty-one percent)</summary>
        public long? TaxPercentage { get; set; }
        /// <summary>Universal Product Code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Upc { get; set; }
#nullable restore
#else
        public string Upc { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.LineItem"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.LineItem CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.LineItem();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amountExcludingTax", n => { AmountExcludingTax = n.GetLongValue(); } },
                { "amountIncludingTax", n => { AmountIncludingTax = n.GetLongValue(); } },
                { "brand", n => { Brand = n.GetStringValue(); } },
                { "color", n => { Color = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "imageUrl", n => { ImageUrl = n.GetStringValue(); } },
                { "itemCategory", n => { ItemCategory = n.GetStringValue(); } },
                { "manufacturer", n => { Manufacturer = n.GetStringValue(); } },
                { "marketplaceSellerId", n => { MarketplaceSellerId = n.GetStringValue(); } },
                { "productUrl", n => { ProductUrl = n.GetStringValue(); } },
                { "quantity", n => { Quantity = n.GetLongValue(); } },
                { "receiverEmail", n => { ReceiverEmail = n.GetStringValue(); } },
                { "size", n => { Size = n.GetStringValue(); } },
                { "sku", n => { Sku = n.GetStringValue(); } },
                { "taxAmount", n => { TaxAmount = n.GetLongValue(); } },
                { "taxPercentage", n => { TaxPercentage = n.GetLongValue(); } },
                { "upc", n => { Upc = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteLongValue("amountExcludingTax", AmountExcludingTax);
            writer.WriteLongValue("amountIncludingTax", AmountIncludingTax);
            writer.WriteStringValue("brand", Brand);
            writer.WriteStringValue("color", Color);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("imageUrl", ImageUrl);
            writer.WriteStringValue("itemCategory", ItemCategory);
            writer.WriteStringValue("manufacturer", Manufacturer);
            writer.WriteStringValue("marketplaceSellerId", MarketplaceSellerId);
            writer.WriteStringValue("productUrl", ProductUrl);
            writer.WriteLongValue("quantity", Quantity);
            writer.WriteStringValue("receiverEmail", ReceiverEmail);
            writer.WriteStringValue("size", Size);
            writer.WriteStringValue("sku", Sku);
            writer.WriteLongValue("taxAmount", TaxAmount);
            writer.WriteLongValue("taxPercentage", TaxPercentage);
            writer.WriteStringValue("upc", Upc);
        }
    }
}
#pragma warning restore CS0618
