// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>
    /// **paybybank_plaid** details
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ManagementServiceV3PaymentMethodPaybybankPlaid : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Merchant logo</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Logo { get; set; }
#nullable restore
#else
        public string Logo { get; set; }
#endif
        /// <summary>Information regarding the transaction description.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PayByBankPlaidResponseInfoTransactionDescription? TransactionDescription { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PayByBankPlaidResponseInfoTransactionDescription TransactionDescription { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3PaymentMethodPaybybankPlaid"/> and sets the default values.
        /// </summary>
        public ManagementServiceV3PaymentMethodPaybybankPlaid()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3PaymentMethodPaybybankPlaid"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3PaymentMethodPaybybankPlaid CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3PaymentMethodPaybybankPlaid();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "logo", n => { Logo = n.GetStringValue(); } },
                { "transactionDescription", n => { TransactionDescription = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PayByBankPlaidResponseInfoTransactionDescription>(global::Soenneker.Adyen.OpenApiClient.Models.PayByBankPlaidResponseInfoTransactionDescription.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("logo", Logo);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PayByBankPlaidResponseInfoTransactionDescription>("transactionDescription", TransactionDescription);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
