// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>
    /// Contains event details.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MerchantCreatedNotificationRequestData : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Key-value pairs that specify the actions that the merchant account can do and its settings. The key is a capability. For example, the **sendToTransferInstrument** is the capability required before you can pay out funds to the bank account. The value is an object containing the settings for the capability.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.MerchantCreatedNotificationRequestDataCapabilities? Capabilities { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.MerchantCreatedNotificationRequestDataCapabilities Capabilities { get; set; }
#endif
        /// <summary>The unique identifier of the company account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CompanyId { get; set; }
#nullable restore
#else
        public string CompanyId { get; set; }
#endif
        /// <summary>The unique identifier of the [legal entity](https://docs.adyen.com/api-explorer/legalentity/latest/post/legalEntities#responses-200-id).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LegalEntityId { get; set; }
#nullable restore
#else
        public string LegalEntityId { get; set; }
#endif
        /// <summary>The unique identifier of the merchant account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MerchantId { get; set; }
#nullable restore
#else
        public string MerchantId { get; set; }
#endif
        /// <summary>The status of the merchant account.Possible values:* **PreActive**: The merchant account has been created. Users cannot access the merchant account in the Customer Area. The account cannot process payments.* **Active**: Users can access the merchant account in the Customer Area. If the company account is also **Active**, then payment processing and payouts are enabled.* **InactiveWithModifications**: Users can access the merchant account in the Customer Area. The account cannot process new payments but can still modify payments, for example issue refunds. The account can still receive payouts.* **Inactive**: Users can access the merchant account in the Customer Area. Payment processing and payouts are disabled.* **Closed**: The account is closed and this cannot be reversed. Users cannot log in. Payment processing and payouts are disabled.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Status { get; set; }
#nullable restore
#else
        public string Status { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.Models.MerchantCreatedNotificationRequestData"/> and sets the default values.
        /// </summary>
        public MerchantCreatedNotificationRequestData()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.MerchantCreatedNotificationRequestData"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.MerchantCreatedNotificationRequestData CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.MerchantCreatedNotificationRequestData();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "capabilities", n => { Capabilities = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.MerchantCreatedNotificationRequestDataCapabilities>(global::Soenneker.Adyen.OpenApiClient.Models.MerchantCreatedNotificationRequestDataCapabilities.CreateFromDiscriminatorValue); } },
                { "companyId", n => { CompanyId = n.GetStringValue(); } },
                { "legalEntityId", n => { LegalEntityId = n.GetStringValue(); } },
                { "merchantId", n => { MerchantId = n.GetStringValue(); } },
                { "status", n => { Status = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.MerchantCreatedNotificationRequestDataCapabilities>("capabilities", Capabilities);
            writer.WriteStringValue("companyId", CompanyId);
            writer.WriteStringValue("legalEntityId", LegalEntityId);
            writer.WriteStringValue("merchantId", MerchantId);
            writer.WriteStringValue("status", Status);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
