// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class MerchantAccount : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>List of terminals assigned to this merchant account as in-store terminals. This means that the terminal is ready to be boarded, or is already boarded.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? InStoreTerminals { get; set; }
#nullable restore
#else
        public List<string> InStoreTerminals { get; set; }
#endif
        /// <summary>List of terminals assigned to the inventory of this merchant account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? InventoryTerminals { get; set; }
#nullable restore
#else
        public List<string> InventoryTerminals { get; set; }
#endif
        /// <summary>The merchant account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MerchantAccountProp { get; set; }
#nullable restore
#else
        public string MerchantAccountProp { get; set; }
#endif
        /// <summary>Array of stores under this merchant account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Adyen.OpenApiClient.Models.TfmApiServiceV1Store>? Stores { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Adyen.OpenApiClient.Models.TfmApiServiceV1Store> Stores { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.MerchantAccount"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.MerchantAccount CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.MerchantAccount();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "inStoreTerminals", n => { InStoreTerminals = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "inventoryTerminals", n => { InventoryTerminals = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "merchantAccount", n => { MerchantAccountProp = n.GetStringValue(); } },
                { "stores", n => { Stores = n.GetCollectionOfObjectValues<global::Soenneker.Adyen.OpenApiClient.Models.TfmApiServiceV1Store>(global::Soenneker.Adyen.OpenApiClient.Models.TfmApiServiceV1Store.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfPrimitiveValues<string>("inStoreTerminals", InStoreTerminals);
            writer.WriteCollectionOfPrimitiveValues<string>("inventoryTerminals", InventoryTerminals);
            writer.WriteStringValue("merchantAccount", MerchantAccountProp);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Adyen.OpenApiClient.Models.TfmApiServiceV1Store>("stores", Stores);
        }
    }
}
#pragma warning restore CS0618
