// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>Possible values:* **Request*** **Response*** **Notification**</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum MessageType
    {
        [EnumMember(Value = "Request")]
        #pragma warning disable CS1591
        Request,
        #pragma warning restore CS1591
        [EnumMember(Value = "Response")]
        #pragma warning disable CS1591
        Response,
        #pragma warning restore CS1591
        [EnumMember(Value = "Notification")]
        #pragma warning disable CS1591
        Notification,
        #pragma warning restore CS1591
    }
}
