// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>The type of event notification sent when you select the notification button.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum Notification_category
    {
        [EnumMember(Value = "SaleWakeUp")]
        #pragma warning disable CS1591
        SaleWakeUp,
        #pragma warning restore CS1591
        [EnumMember(Value = "KeyPressed")]
        #pragma warning disable CS1591
        KeyPressed,
        #pragma warning restore CS1591
    }
}
