// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Opi : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Indicates if Pay at table is enabled.</summary>
        public bool? EnablePayAtTable { get; set; }
        /// <summary>The store number to use for Pay at Table.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PayAtTableStoreNumber { get; set; }
#nullable restore
#else
        public string PayAtTableStoreNumber { get; set; }
#endif
        /// <summary>The URL and port number used for Pay at Table communication.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? PayAtTableURL { get; set; }
#nullable restore
#else
        public string PayAtTableURL { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.Opi"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.Opi CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.Opi();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "enablePayAtTable", n => { EnablePayAtTable = n.GetBoolValue(); } },
                { "payAtTableStoreNumber", n => { PayAtTableStoreNumber = n.GetStringValue(); } },
                { "payAtTableURL", n => { PayAtTableURL = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("enablePayAtTable", EnablePayAtTable);
            writer.WriteStringValue("payAtTableStoreNumber", PayAtTableStoreNumber);
            writer.WriteStringValue("payAtTableURL", PayAtTableURL);
        }
    }
}
#pragma warning restore CS0618
