// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>
    /// Configuration for creating redundant payment tokens with third-party token vaults using the Adyen Forward API. This feature requires Forward API webhook integration and pre-configured templates in your Adyen account. Contact your Adyen account manager for setup and availability.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaymentRequestThirdPartyTokenRedundancyInfo : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Request-specific parameter values to populate the template placeholders. Each key must match a placeholder defined in the template referenced by `requestTemplateCode`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentRequestThirdPartyTokenRedundancyInfoRequestParameters? RequestParameters { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentRequestThirdPartyTokenRedundancyInfoRequestParameters RequestParameters { get; set; }
#endif
        /// <summary>Identifier for the third-party token request template configured in your Adyen account. This template defines the structure and endpoint for token requests.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? RequestTemplateCode { get; set; }
#nullable restore
#else
        public string RequestTemplateCode { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.Models.PaymentRequestThirdPartyTokenRedundancyInfo"/> and sets the default values.
        /// </summary>
        public PaymentRequestThirdPartyTokenRedundancyInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.PaymentRequestThirdPartyTokenRedundancyInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.PaymentRequestThirdPartyTokenRedundancyInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.PaymentRequestThirdPartyTokenRedundancyInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "requestParameters", n => { RequestParameters = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentRequestThirdPartyTokenRedundancyInfoRequestParameters>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentRequestThirdPartyTokenRedundancyInfoRequestParameters.CreateFromDiscriminatorValue); } },
                { "requestTemplateCode", n => { RequestTemplateCode = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentRequestThirdPartyTokenRedundancyInfoRequestParameters>("requestParameters", RequestParameters);
            writer.WriteStringValue("requestTemplateCode", RequestTemplateCode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
