// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PaymentMethodSetupInfo : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Details to provide if `type` is **accel**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAccel? Accel { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAccel Accel { get; set; }
#endif
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Details to provide if `type` is **affirm**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAffirm? Affirm { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAffirm Affirm { get; set; }
#endif
        /// <summary>Details to provide if `type` is **afterpaytouch**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAfterpayTouch? AfterpayTouch { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAfterpayTouch AfterpayTouch { get; set; }
#endif
        /// <summary>Details to provide if `type` is **alipay_plus**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAlipayPlus? AlipayPlus { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAlipayPlus AlipayPlus { get; set; }
#endif
        /// <summary>Details to provide if `type` is **amex**.For merchants operating in Australia, New Zealand &amp; Canada, JCB and American Express are automatically requested together.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAmex? Amex { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAmex Amex { get; set; }
#endif
        /// <summary>Details to provide if `type` is **applepay**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoApplePay? ApplePay { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoApplePay ApplePay { get; set; }
#endif
        /// <summary>Details to provide if `type` is **bcmc** (Bancontact).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoBcmc? Bcmc { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoBcmc Bcmc { get; set; }
#endif
        /// <summary>The unique identifier of the business line. Required if you are a [platform model](https://docs.adyen.com/platforms).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? BusinessLineId { get; set; }
#nullable restore
#else
        public string BusinessLineId { get; set; }
#endif
        /// <summary>Details to provide if `type` is **carnet**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoCarnet? Carnet { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoCarnet Carnet { get; set; }
#endif
        /// <summary>Details to provide if `type` is **cartebancaire**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoCartesBancaires? CartesBancaires { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoCartesBancaires CartesBancaires { get; set; }
#endif
        /// <summary>Details to provide if `type` is **clearpay**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoClearpay? Clearpay { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoClearpay Clearpay { get; set; }
#endif
        /// <summary>The list of countries where a payment method is available. By default, all countries supported by the payment method.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Countries { get; set; }
#nullable restore
#else
        public List<string> Countries { get; set; }
#endif
        /// <summary>Details to provide if `type` is **cup** (China Union Pay).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoCup? Cup { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoCup Cup { get; set; }
#endif
        /// <summary>The list of currencies that a payment method supports. By default, all currencies supported by the payment method.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Currencies { get; set; }
#nullable restore
#else
        public List<string> Currencies { get; set; }
#endif
        /// <summary>The list of custom routing flags to route payment to the intended acquirer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CustomRoutingFlags { get; set; }
#nullable restore
#else
        public List<string> CustomRoutingFlags { get; set; }
#endif
        /// <summary>Details to provide if `type` is **diners**.For merchants operating in Japan, Diners payments are processed through the JCB network. This means that you must include [JCB-specific fields](https://docs.adyen.com/api-explorer/Management/latest/post/merchants/(merchantId)/paymentMethodSettings/(paymentMethodId)#request-jcb) in this object.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoDiners? Diners { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoDiners Diners { get; set; }
#endif
        /// <summary>Details to provide if `type` is **discover**.For merchants operating in Japan, request [Diners](https://docs.adyen.com/api-explorer/Management/latest/post/merchants/(merchantId)/paymentMethodSettings/(paymentMethodId)#request-diners) payment method instead. Discover is automatically requested, together with Diners.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoDiscover? Discover { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoDiscover Discover { get; set; }
#endif
        /// <summary>Details to provide if `type` is **eft_directdebit_CA** (EFT PAD).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoEftDirectdebitCa? EftDirectdebitCA { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoEftDirectdebitCa EftDirectdebitCA { get; set; }
#endif
        /// <summary>Details to provide if `type` is **eftpos_australia**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoEftposAustralia? EftposAustralia { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoEftposAustralia EftposAustralia { get; set; }
#endif
        /// <summary>Details to provide if `type` is **girocard**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoGirocard? Girocard { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoGirocard Girocard { get; set; }
#endif
        /// <summary>Details to provide if `type` is **givex**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoGivex? Givex { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoGivex Givex { get; set; }
#endif
        /// <summary>Details to provide if `type` is **googlepay**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoGooglePay? GooglePay { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoGooglePay GooglePay { get; set; }
#endif
        /// <summary>Details to provide if `type` is **ideal**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoIdeal? Ideal { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoIdeal Ideal { get; set; }
#endif
        /// <summary>Details to provide if `type` is **interac_card**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoInteracCard? InteracCard { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoInteracCard InteracCard { get; set; }
#endif
        /// <summary>The jcb property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.JcbInfo? Jcb { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.JcbInfo Jcb { get; set; }
#endif
        /// <summary>Details to provide if `type` is **klarna** or its variant.You can use the following payment method `type` values for Klarna:* **klarna**: Klarna Pay Later* **klarna_account**: Klarna Pay over time* **klarna_paynow**: Klarna Pay now* **klarna_b2b**: [Billie via Klarna](https://docs.adyen.com/payment-methods/klarna/billie)</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoKlarna? Klarna { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoKlarna Klarna { get; set; }
#endif
        /// <summary>Details to provide if `type` is **maestro**.In the US, `maestro` is not supported; use `maestro_usa` instead. </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoMaestro? Maestro { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoMaestro Maestro { get; set; }
#endif
        /// <summary>Details to provide if `type` is **maestro_usa**.Only for Maestro USA, otherwise use `maestro`.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoMaestroUsa? MaestroUsa { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoMaestroUsa MaestroUsa { get; set; }
#endif
        /// <summary>Details to provide if `type` is **mc**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoMc? Mc { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoMc Mc { get; set; }
#endif
        /// <summary>The mealVoucher_FR property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.MealVoucherFrInfo? MealVoucherFR { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.MealVoucherFrInfo MealVoucherFR { get; set; }
#endif
        /// <summary>Details to provide if `type` is **nyce**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoNyce? Nyce { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoNyce Nyce { get; set; }
#endif
        /// <summary>Details to provide if `type` is **paybybank_plaid**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPaybybankPlaid? PaybybankPlaid { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPaybybankPlaid PaybybankPlaid { get; set; }
#endif
        /// <summary>Details to provide if `type` is **payme**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPayme? Payme { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPayme Payme { get; set; }
#endif
        /// <summary>Details to provide if `type` is **paypal**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPaypal? Paypal { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPaypal Paypal { get; set; }
#endif
        /// <summary>Details to provide if `type` is **payto**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPayto? Payto { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPayto Payto { get; set; }
#endif
        /// <summary>Details to provide if `type` is **pulse**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPulse? Pulse { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPulse Pulse { get; set; }
#endif
        /// <summary>Your reference for the payment method. Supported characters a-z, A-Z, 0-9.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reference { get; set; }
#nullable restore
#else
        public string Reference { get; set; }
#endif
        /// <summary>Details to provide if `type` is **sepadirectdebit**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSepadirectdebit? Sepadirectdebit { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSepadirectdebit Sepadirectdebit { get; set; }
#endif
        /// <summary>The sales channel. Required if:- The merchant account does not have a sales channel.- `type` is **alipay**.When you provide this field, it overrides the default sales channel set on the merchant account.Possible values: **eCommerce**, **pos**, **contAuth**, and **moto**. </summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoShopperInteraction? ShopperInteraction { get; set; }
        /// <summary>Details to provide if `type` is **sodexo**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSodexo? Sodexo { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSodexo Sodexo { get; set; }
#endif
        /// <summary>Sofort details.</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSofort? Sofort { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSofort Sofort { get; set; }
#endif
        /// <summary>Details to provide if `type` is **star**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoStar? Star { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoStar Star { get; set; }
#endif
        /// <summary>The unique identifier of the store for which to configure the payment method, if any.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? StoreIds { get; set; }
#nullable restore
#else
        public List<string> StoreIds { get; set; }
#endif
        /// <summary>Details to provide if `type` is **svs**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSvs? Svs { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSvs Svs { get; set; }
#endif
        /// <summary>Details to provide if `type` is **swish**. - This field is required only if you have a contract with Swish. Swish handles settlement directly with you (not through Adyen). - If not specified then it&apos;s assumed that you are using Adyen&apos;s contract with Swish.You don&apos;t have a direct relationship with Swish.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSwish? Swish { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSwish Swish { get; set; }
#endif
        /// <summary>Details to provide if `type` is **ticket** (Edenred Brazil).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoTicket? Ticket { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoTicket Ticket { get; set; }
#endif
        /// <summary>Details to provide if `type` is **twint**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoTwint? Twint { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoTwint Twint { get; set; }
#endif
        /// <summary>Payment method [variant](https://docs.adyen.com/development-resources/paymentmethodvariant#management-api).</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoType? Type { get; set; }
        /// <summary>Details to provide if `type` is **valuelink**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoValuelink? Valuelink { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoValuelink Valuelink { get; set; }
#endif
        /// <summary>Details to provide if `type` is **vipps**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoVipps? Vipps { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoVipps Vipps { get; set; }
#endif
        /// <summary>Details to provide if `type` is **visa**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoVisa? Visa { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoVisa Visa { get; set; }
#endif
        /// <summary>Details to provide if `type` is **wechatpay**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoWechatpay? Wechatpay { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoWechatpay Wechatpay { get; set; }
#endif
        /// <summary>Details to provide if `type` is **wechatpay_pos**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoWechatpayPos? WechatpayPos { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoWechatpayPos WechatpayPos { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfo"/> and sets the default values.
        /// </summary>
        public PaymentMethodSetupInfo()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accel", n => { Accel = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAccel>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAccel.CreateFromDiscriminatorValue); } },
                { "affirm", n => { Affirm = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAffirm>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAffirm.CreateFromDiscriminatorValue); } },
                { "afterpayTouch", n => { AfterpayTouch = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAfterpayTouch>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAfterpayTouch.CreateFromDiscriminatorValue); } },
                { "alipayPlus", n => { AlipayPlus = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAlipayPlus>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAlipayPlus.CreateFromDiscriminatorValue); } },
                { "amex", n => { Amex = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAmex>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAmex.CreateFromDiscriminatorValue); } },
                { "applePay", n => { ApplePay = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoApplePay>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoApplePay.CreateFromDiscriminatorValue); } },
                { "bcmc", n => { Bcmc = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoBcmc>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoBcmc.CreateFromDiscriminatorValue); } },
                { "businessLineId", n => { BusinessLineId = n.GetStringValue(); } },
                { "carnet", n => { Carnet = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoCarnet>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoCarnet.CreateFromDiscriminatorValue); } },
                { "cartesBancaires", n => { CartesBancaires = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoCartesBancaires>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoCartesBancaires.CreateFromDiscriminatorValue); } },
                { "clearpay", n => { Clearpay = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoClearpay>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoClearpay.CreateFromDiscriminatorValue); } },
                { "countries", n => { Countries = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "cup", n => { Cup = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoCup>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoCup.CreateFromDiscriminatorValue); } },
                { "currencies", n => { Currencies = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "customRoutingFlags", n => { CustomRoutingFlags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "diners", n => { Diners = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoDiners>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoDiners.CreateFromDiscriminatorValue); } },
                { "discover", n => { Discover = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoDiscover>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoDiscover.CreateFromDiscriminatorValue); } },
                { "eft_directdebit_CA", n => { EftDirectdebitCA = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoEftDirectdebitCa>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoEftDirectdebitCa.CreateFromDiscriminatorValue); } },
                { "eftpos_australia", n => { EftposAustralia = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoEftposAustralia>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoEftposAustralia.CreateFromDiscriminatorValue); } },
                { "girocard", n => { Girocard = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoGirocard>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoGirocard.CreateFromDiscriminatorValue); } },
                { "givex", n => { Givex = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoGivex>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoGivex.CreateFromDiscriminatorValue); } },
                { "googlePay", n => { GooglePay = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoGooglePay>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoGooglePay.CreateFromDiscriminatorValue); } },
                { "ideal", n => { Ideal = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoIdeal>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoIdeal.CreateFromDiscriminatorValue); } },
                { "interac_card", n => { InteracCard = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoInteracCard>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoInteracCard.CreateFromDiscriminatorValue); } },
                { "jcb", n => { Jcb = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.JcbInfo>(global::Soenneker.Adyen.OpenApiClient.Models.JcbInfo.CreateFromDiscriminatorValue); } },
                { "klarna", n => { Klarna = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoKlarna>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoKlarna.CreateFromDiscriminatorValue); } },
                { "maestro", n => { Maestro = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoMaestro>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoMaestro.CreateFromDiscriminatorValue); } },
                { "maestro_usa", n => { MaestroUsa = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoMaestroUsa>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoMaestroUsa.CreateFromDiscriminatorValue); } },
                { "mc", n => { Mc = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoMc>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoMc.CreateFromDiscriminatorValue); } },
                { "mealVoucher_FR", n => { MealVoucherFR = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.MealVoucherFrInfo>(global::Soenneker.Adyen.OpenApiClient.Models.MealVoucherFrInfo.CreateFromDiscriminatorValue); } },
                { "nyce", n => { Nyce = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoNyce>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoNyce.CreateFromDiscriminatorValue); } },
                { "paybybank_plaid", n => { PaybybankPlaid = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPaybybankPlaid>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPaybybankPlaid.CreateFromDiscriminatorValue); } },
                { "payme", n => { Payme = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPayme>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPayme.CreateFromDiscriminatorValue); } },
                { "paypal", n => { Paypal = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPaypal>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPaypal.CreateFromDiscriminatorValue); } },
                { "payto", n => { Payto = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPayto>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPayto.CreateFromDiscriminatorValue); } },
                { "pulse", n => { Pulse = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPulse>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPulse.CreateFromDiscriminatorValue); } },
                { "reference", n => { Reference = n.GetStringValue(); } },
                { "sepadirectdebit", n => { Sepadirectdebit = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSepadirectdebit>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSepadirectdebit.CreateFromDiscriminatorValue); } },
                { "shopperInteraction", n => { ShopperInteraction = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoShopperInteraction>(); } },
                { "sodexo", n => { Sodexo = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSodexo>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSodexo.CreateFromDiscriminatorValue); } },
                { "sofort", n => { Sofort = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSofort>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSofort.CreateFromDiscriminatorValue); } },
                { "star", n => { Star = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoStar>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoStar.CreateFromDiscriminatorValue); } },
                { "storeIds", n => { StoreIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "svs", n => { Svs = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSvs>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSvs.CreateFromDiscriminatorValue); } },
                { "swish", n => { Swish = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSwish>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSwish.CreateFromDiscriminatorValue); } },
                { "ticket", n => { Ticket = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoTicket>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoTicket.CreateFromDiscriminatorValue); } },
                { "twint", n => { Twint = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoTwint>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoTwint.CreateFromDiscriminatorValue); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoType>(); } },
                { "valuelink", n => { Valuelink = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoValuelink>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoValuelink.CreateFromDiscriminatorValue); } },
                { "vipps", n => { Vipps = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoVipps>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoVipps.CreateFromDiscriminatorValue); } },
                { "visa", n => { Visa = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoVisa>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoVisa.CreateFromDiscriminatorValue); } },
                { "wechatpay", n => { Wechatpay = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoWechatpay>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoWechatpay.CreateFromDiscriminatorValue); } },
                { "wechatpay_pos", n => { WechatpayPos = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoWechatpayPos>(global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoWechatpayPos.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAccel>("accel", Accel);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAffirm>("affirm", Affirm);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAfterpayTouch>("afterpayTouch", AfterpayTouch);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAlipayPlus>("alipayPlus", AlipayPlus);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoAmex>("amex", Amex);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoApplePay>("applePay", ApplePay);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoBcmc>("bcmc", Bcmc);
            writer.WriteStringValue("businessLineId", BusinessLineId);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoCarnet>("carnet", Carnet);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoCartesBancaires>("cartesBancaires", CartesBancaires);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoClearpay>("clearpay", Clearpay);
            writer.WriteCollectionOfPrimitiveValues<string>("countries", Countries);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoCup>("cup", Cup);
            writer.WriteCollectionOfPrimitiveValues<string>("currencies", Currencies);
            writer.WriteCollectionOfPrimitiveValues<string>("customRoutingFlags", CustomRoutingFlags);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoDiners>("diners", Diners);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoDiscover>("discover", Discover);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoEftDirectdebitCa>("eft_directdebit_CA", EftDirectdebitCA);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoEftposAustralia>("eftpos_australia", EftposAustralia);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoGirocard>("girocard", Girocard);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoGivex>("givex", Givex);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoGooglePay>("googlePay", GooglePay);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoIdeal>("ideal", Ideal);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoInteracCard>("interac_card", InteracCard);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.JcbInfo>("jcb", Jcb);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoKlarna>("klarna", Klarna);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoMaestro>("maestro", Maestro);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoMaestroUsa>("maestro_usa", MaestroUsa);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoMc>("mc", Mc);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.MealVoucherFrInfo>("mealVoucher_FR", MealVoucherFR);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoNyce>("nyce", Nyce);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPaybybankPlaid>("paybybank_plaid", PaybybankPlaid);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPayme>("payme", Payme);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPaypal>("paypal", Paypal);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPayto>("payto", Payto);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoPulse>("pulse", Pulse);
            writer.WriteStringValue("reference", Reference);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSepadirectdebit>("sepadirectdebit", Sepadirectdebit);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoShopperInteraction>("shopperInteraction", ShopperInteraction);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSodexo>("sodexo", Sodexo);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSofort>("sofort", Sofort);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoStar>("star", Star);
            writer.WriteCollectionOfPrimitiveValues<string>("storeIds", StoreIds);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSvs>("svs", Svs);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoSwish>("swish", Swish);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoTicket>("ticket", Ticket);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoTwint>("twint", Twint);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoType>("type", Type);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoValuelink>("valuelink", Valuelink);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoVipps>("vipps", Vipps);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoVisa>("visa", Visa);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoWechatpay>("wechatpay", Wechatpay);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PaymentMethodSetupInfoWechatpayPos>("wechatpay_pos", WechatpayPos);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
