// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>
    /// The fraud result properties of the payment.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PaymentResultFraudResult : IAdditionalDataHolder, IParsable
    {
        /// <summary>The total fraud score generated by the risk checks.</summary>
        public int? AccountScore { get; set; }
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The result of the individual risk checks.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Adyen.OpenApiClient.Models.FraudCheckResultWrapper>? Results { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Adyen.OpenApiClient.Models.FraudCheckResultWrapper> Results { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.Models.PaymentResultFraudResult"/> and sets the default values.
        /// </summary>
        public PaymentResultFraudResult()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.PaymentResultFraudResult"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.PaymentResultFraudResult CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.PaymentResultFraudResult();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accountScore", n => { AccountScore = n.GetIntValue(); } },
                { "results", n => { Results = n.GetCollectionOfObjectValues<global::Soenneker.Adyen.OpenApiClient.Models.FraudCheckResultWrapper>(global::Soenneker.Adyen.OpenApiClient.Models.FraudCheckResultWrapper.CreateFromDiscriminatorValue)?.AsList(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteIntValue("accountScore", AccountScore);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Adyen.OpenApiClient.Models.FraudCheckResultWrapper>("results", Results);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
