// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>Indicates if the printer is working and usable.Possible values:* **NoPaper*** **OK*** **OutOfOrder*** **PaperJam*** **PaperLow**</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum PrinterStatus
    {
        [EnumMember(Value = "NoPaper")]
        #pragma warning disable CS1591
        NoPaper,
        #pragma warning restore CS1591
        [EnumMember(Value = "OK")]
        #pragma warning disable CS1591
        OK,
        #pragma warning restore CS1591
        [EnumMember(Value = "OutOfOrder")]
        #pragma warning disable CS1591
        OutOfOrder,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaperJam")]
        #pragma warning disable CS1591
        PaperJam,
        #pragma warning restore CS1591
        [EnumMember(Value = "PaperLow")]
        #pragma warning disable CS1591
        PaperLow,
        #pragma warning restore CS1591
    }
}
