// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class PrintOutput : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The DocumentQualifier property</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.DocumentQualifier? DocumentQualifier { get; set; }
        /// <summary>Type of the print integrated in other prints. Allows a separated printing (paper cut if available), or integration with the sale receipt or other print. If the printing is integrated, the response is always immediate, even if the `ResponseMode` is set to `PrintEnd`.</summary>
        public bool? IntegratedPrintFlag { get; set; }
        /// <summary>Content to display or print.This is a sequence of elements if they have different formats.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.OutputContent? OutputContent { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.OutputContent OutputContent { get; set; }
#endif
        /// <summary>Indicates that the cardholder payment receipt requires a physical signature by the Customer.</summary>
        public bool? RequiredSignatureFlag { get; set; }
        /// <summary>The ResponseMode property</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.ResponseMode? ResponseMode { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.Models.PrintOutput"/> and sets the default values.
        /// </summary>
        public PrintOutput()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.PrintOutput"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.PrintOutput CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.PrintOutput();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "DocumentQualifier", n => { DocumentQualifier = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.DocumentQualifier>(); } },
                { "IntegratedPrintFlag", n => { IntegratedPrintFlag = n.GetBoolValue(); } },
                { "OutputContent", n => { OutputContent = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.OutputContent>(global::Soenneker.Adyen.OpenApiClient.Models.OutputContent.CreateFromDiscriminatorValue); } },
                { "RequiredSignatureFlag", n => { RequiredSignatureFlag = n.GetBoolValue(); } },
                { "ResponseMode", n => { ResponseMode = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.ResponseMode>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.DocumentQualifier>("DocumentQualifier", DocumentQualifier);
            writer.WriteBoolValue("IntegratedPrintFlag", IntegratedPrintFlag);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.OutputContent>("OutputContent", OutputContent);
            writer.WriteBoolValue("RequiredSignatureFlag", RequiredSignatureFlag);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.ResponseMode>("ResponseMode", ResponseMode);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
