// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class RecurringTopUp : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The counterparty property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.TopUpCounterparty? Counterparty { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.TopUpCounterparty Counterparty { get; set; }
#endif
        /// <summary>Your description for the recurring top-up.Maximum length is 140 characters. If you set a longer description, it will be cut off at 140 characters.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The unique identifier of the top up.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; private set; }
#nullable restore
#else
        public string Id { get; private set; }
#endif
        /// <summary> A reference that is sent to the recipient. This reference is also sent in all webhooks related to the transfer, so you can use it to track statuses for both parties involved in the funds movement. Supported characters: **a-z**, **A-Z**, **0-9**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ReferenceForBeneficiary { get; set; }
#nullable restore
#else
        public string ReferenceForBeneficiary { get; set; }
#endif
        /// <summary>The status of the recurring top-up. If not provided, by default, this is set to **active**.Possible values:  * **active**:  the top up is enabled and funds will be pulled in. * **inactive**: the top up is disabled and cannot be triggered. </summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.RecurringTopUpStatus? Status { get; set; }
        /// <summary>The topUpAmount property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.TopUpAmount? TopUpAmount { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.TopUpAmount TopUpAmount { get; set; }
#endif
        /// <summary>The trigger property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.Trigger? Trigger { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.Trigger Trigger { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.Models.RecurringTopUp"/> and sets the default values.
        /// </summary>
        public RecurringTopUp()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.RecurringTopUp"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.RecurringTopUp CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.RecurringTopUp();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "counterparty", n => { Counterparty = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.TopUpCounterparty>(global::Soenneker.Adyen.OpenApiClient.Models.TopUpCounterparty.CreateFromDiscriminatorValue); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "referenceForBeneficiary", n => { ReferenceForBeneficiary = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.RecurringTopUpStatus>(); } },
                { "topUpAmount", n => { TopUpAmount = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.TopUpAmount>(global::Soenneker.Adyen.OpenApiClient.Models.TopUpAmount.CreateFromDiscriminatorValue); } },
                { "trigger", n => { Trigger = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.Trigger>(global::Soenneker.Adyen.OpenApiClient.Models.Trigger.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.TopUpCounterparty>("counterparty", Counterparty);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("referenceForBeneficiary", ReferenceForBeneficiary);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.RecurringTopUpStatus>("status", Status);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.TopUpAmount>("topUpAmount", TopUpAmount);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.Trigger>("trigger", Trigger);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
