// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>
    /// Result of a message request processing.If Result is Success, `ErrorCondition` is absent or not used in the processing of the message. In the other cases, the `ErrorCondition` has to be present and can refine the processing of the message response. `AdditionalResponse` gives more information about the success or the failure of the message request processing, for logging without real time involvements.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ResponseValue : IAdditionalDataHolder, IParsable
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>Additional information related to processing status of a message request.If present, the POI logs it for further examination.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AdditionalResponse { get; set; }
#nullable restore
#else
        public string AdditionalResponse { get; set; }
#endif
        /// <summary>Possible values:* **Aborted*** **Busy*** **Cancel*** **DeviceOut*** **InsertedCard*** **InProgress*** **LoggedOut*** **MessageFormat*** **NotAllowed*** **NotFound*** **PaymentRestriction*** **Refusal*** **UnavailableDevice*** **UnavailableService*** **InvalidCard*** **UnreachableHost*** **WrongPIN**</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.ErrorCondition? ErrorCondition { get; set; }
        /// <summary>Possible values:* **Success*** **Failure*** **Partial**</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.TerminalApiV1Result? Result { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.Models.ResponseValue"/> and sets the default values.
        /// </summary>
        public ResponseValue()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.ResponseValue"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.ResponseValue CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.ResponseValue();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "AdditionalResponse", n => { AdditionalResponse = n.GetStringValue(); } },
                { "ErrorCondition", n => { ErrorCondition = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.ErrorCondition>(); } },
                { "Result", n => { Result = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TerminalApiV1Result>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("AdditionalResponse", AdditionalResponse);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.ErrorCondition>("ErrorCondition", ErrorCondition);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TerminalApiV1Result>("Result", Result);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
