// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum ScaDeviceType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "browser")]
        #pragma warning disable CS1591
        Browser,
        #pragma warning restore CS1591
        [EnumMember(Value = "ios")]
        #pragma warning disable CS1591
        Ios,
        #pragma warning restore CS1591
        [EnumMember(Value = "android")]
        #pragma warning disable CS1591
        Android,
        #pragma warning restore CS1591
    }
}
