// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>The Secure Remote Commerce scheme.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SecureRemoteCommerceCheckoutData_scheme
    {
        [EnumMember(Value = "mc")]
        #pragma warning disable CS1591
        Mc,
        #pragma warning restore CS1591
        [EnumMember(Value = "visa")]
        #pragma warning disable CS1591
        Visa,
        #pragma warning restore CS1591
    }
}
