// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class StoredPaymentMethodResource : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The alias of the credit card number.Applies only to recurring contracts storing credit card details</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Alias { get; set; }
#nullable restore
#else
        public string Alias { get; set; }
#endif
        /// <summary>The alias type of the credit card number.Applies only to recurring contracts storing credit card details.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AliasType { get; set; }
#nullable restore
#else
        public string AliasType { get; set; }
#endif
        /// <summary>The billingAddress property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.CheckoutServiceV72Address? BillingAddress { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.CheckoutServiceV72Address BillingAddress { get; set; }
#endif
        /// <summary>The brand of the card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Brand { get; set; }
#nullable restore
#else
        public string Brand { get; set; }
#endif
        /// <summary>The bank identification number (BIN) of the card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? CardBin { get; set; }
#nullable restore
#else
        public string CardBin { get; set; }
#endif
        /// <summary>The date when the recurring details were created.</summary>
        public DateTimeOffset? CreatedAt { get; set; }
        /// <summary>The month the card expires.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExpiryMonth { get; set; }
#nullable restore
#else
        public string ExpiryMonth { get; set; }
#endif
        /// <summary>The last two digits of the year the card expires. For example, **22** for the year 2022.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExpiryYear { get; set; }
#nullable restore
#else
        public string ExpiryYear { get; set; }
#endif
        /// <summary>The response code returned by an external system (for example after a provisioning operation).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalResponseCode { get; set; }
#nullable restore
#else
        public string ExternalResponseCode { get; set; }
#endif
        /// <summary>The token reference of a linked token in an external system (for example a network token reference).</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ExternalTokenReference { get; set; }
#nullable restore
#else
        public string ExternalTokenReference { get; set; }
#endif
        /// <summary>The PSP reference of the first payment that created this recurring detail.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FirstPspReference { get; set; }
#nullable restore
#else
        public string FirstPspReference { get; set; }
#endif
        /// <summary>The unique payment method code.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? HolderName { get; set; }
#nullable restore
#else
        public string HolderName { get; set; }
#endif
        /// <summary>The IBAN of the bank account.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Iban { get; set; }
#nullable restore
#else
        public string Iban { get; set; }
#endif
        /// <summary>A unique identifier of this stored payment method.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The name of the issuer of token or card.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? IssuerName { get; set; }
#nullable restore
#else
        public string IssuerName { get; set; }
#endif
        /// <summary>The last four digits of the PAN.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LastFour { get; set; }
#nullable restore
#else
        public string LastFour { get; set; }
#endif
        /// <summary>The mandate property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.TokenMandate? Mandate { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.TokenMandate Mandate { get; set; }
#endif
        /// <summary>The display name of the stored payment method.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>Returned in the response if you are not tokenizing with Adyen and are using the Merchant-initiated transactions (MIT) framework from Mastercard or Visa.This contains either the Mastercard Trace ID or the Visa Transaction ID.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? NetworkTxReference { get; set; }
#nullable restore
#else
        public string NetworkTxReference { get; set; }
#endif
        /// <summary>The name of the bank account holder.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? OwnerName { get; set; }
#nullable restore
#else
        public string OwnerName { get; set; }
#endif
        /// <summary>The shopper’s email address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShopperEmail { get; set; }
#nullable restore
#else
        public string ShopperEmail { get; set; }
#endif
        /// <summary>Your reference to uniquely identify this shopper, for example user ID or account ID. The value is case-sensitive and must be at least three characters.&gt; Your reference must not include personally identifiable information (PII) such as name or email address.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ShopperReference { get; set; }
#nullable restore
#else
        public string ShopperReference { get; set; }
#endif
        /// <summary>Defines a recurring payment type.Allowed values:* `Subscription` – A transaction for a fixed or variable amount, which follows a fixed schedule.* `CardOnFile` – With a card-on-file (CoF) transaction, card details are stored to enable one-click or omnichannel journeys, or simply to streamline the checkout process. Any subscription not following a fixed schedule is also considered a card-on-file transaction.* `UnscheduledCardOnFile` – An unscheduled card-on-file (UCoF) transaction is a transaction that occurs on a non-fixed schedule and/or have variable amounts. For example, automatic top-ups when a cardholder&apos;s balance drops below a certain amount.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? SupportedRecurringProcessingModels { get; set; }
#nullable restore
#else
        public List<string> SupportedRecurringProcessingModels { get; set; }
#endif
        /// <summary>The type of payment method.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.StoredPaymentMethodResource"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.StoredPaymentMethodResource CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.StoredPaymentMethodResource();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "alias", n => { Alias = n.GetStringValue(); } },
                { "aliasType", n => { AliasType = n.GetStringValue(); } },
                { "billingAddress", n => { BillingAddress = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CheckoutServiceV72Address>(global::Soenneker.Adyen.OpenApiClient.Models.CheckoutServiceV72Address.CreateFromDiscriminatorValue); } },
                { "brand", n => { Brand = n.GetStringValue(); } },
                { "cardBin", n => { CardBin = n.GetStringValue(); } },
                { "createdAt", n => { CreatedAt = n.GetDateTimeOffsetValue(); } },
                { "expiryMonth", n => { ExpiryMonth = n.GetStringValue(); } },
                { "expiryYear", n => { ExpiryYear = n.GetStringValue(); } },
                { "externalResponseCode", n => { ExternalResponseCode = n.GetStringValue(); } },
                { "externalTokenReference", n => { ExternalTokenReference = n.GetStringValue(); } },
                { "firstPspReference", n => { FirstPspReference = n.GetStringValue(); } },
                { "holderName", n => { HolderName = n.GetStringValue(); } },
                { "iban", n => { Iban = n.GetStringValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "issuerName", n => { IssuerName = n.GetStringValue(); } },
                { "lastFour", n => { LastFour = n.GetStringValue(); } },
                { "mandate", n => { Mandate = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.TokenMandate>(global::Soenneker.Adyen.OpenApiClient.Models.TokenMandate.CreateFromDiscriminatorValue); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "networkTxReference", n => { NetworkTxReference = n.GetStringValue(); } },
                { "ownerName", n => { OwnerName = n.GetStringValue(); } },
                { "shopperEmail", n => { ShopperEmail = n.GetStringValue(); } },
                { "shopperReference", n => { ShopperReference = n.GetStringValue(); } },
                { "supportedRecurringProcessingModels", n => { SupportedRecurringProcessingModels = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("alias", Alias);
            writer.WriteStringValue("aliasType", AliasType);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CheckoutServiceV72Address>("billingAddress", BillingAddress);
            writer.WriteStringValue("brand", Brand);
            writer.WriteStringValue("cardBin", CardBin);
            writer.WriteDateTimeOffsetValue("createdAt", CreatedAt);
            writer.WriteStringValue("expiryMonth", ExpiryMonth);
            writer.WriteStringValue("expiryYear", ExpiryYear);
            writer.WriteStringValue("externalResponseCode", ExternalResponseCode);
            writer.WriteStringValue("externalTokenReference", ExternalTokenReference);
            writer.WriteStringValue("firstPspReference", FirstPspReference);
            writer.WriteStringValue("holderName", HolderName);
            writer.WriteStringValue("iban", Iban);
            writer.WriteStringValue("id", Id);
            writer.WriteStringValue("issuerName", IssuerName);
            writer.WriteStringValue("lastFour", LastFour);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.TokenMandate>("mandate", Mandate);
            writer.WriteStringValue("name", Name);
            writer.WriteStringValue("networkTxReference", NetworkTxReference);
            writer.WriteStringValue("ownerName", OwnerName);
            writer.WriteStringValue("shopperEmail", ShopperEmail);
            writer.WriteStringValue("shopperReference", ShopperReference);
            writer.WriteCollectionOfPrimitiveValues<string>("supportedRecurringProcessingModels", SupportedRecurringProcessingModels);
            writer.WriteStringValue("type", Type);
        }
    }
}
#pragma warning restore CS0618
