// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>Possible values:* **CashierDisplay*** **CustomerDisplay*** **CashierInput*** **CustomerInput**</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TerminalApiV1Device
    {
        [EnumMember(Value = "CashierDisplay")]
        #pragma warning disable CS1591
        CashierDisplay,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerDisplay")]
        #pragma warning disable CS1591
        CustomerDisplay,
        #pragma warning restore CS1591
        [EnumMember(Value = "CashierInput")]
        #pragma warning disable CS1591
        CashierInput,
        #pragma warning restore CS1591
        [EnumMember(Value = "CustomerInput")]
        #pragma warning disable CS1591
        CustomerInput,
        #pragma warning restore CS1591
    }
}
