// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>Notification message. It informs about the outcome of the operation. Possible values:* CREATED* ALREADY_EXISTS* ERROR</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TestCardRangeCreationResultCreationResultCode
    {
        [EnumMember(Value = "ALREADY_EXISTS")]
        #pragma warning disable CS1591
        AlreadyExists,
        #pragma warning restore CS1591
        [EnumMember(Value = "CREATED")]
        #pragma warning disable CS1591
        Created,
        #pragma warning restore CS1591
        [EnumMember(Value = "ERROR")]
        #pragma warning disable CS1591
        Error,
        #pragma warning restore CS1591
    }
}
