// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>The terminal display mode. Possible values: **dark**, **light**.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum ThemeUpdateRequestMode
    {
        [EnumMember(Value = "dark")]
        #pragma warning disable CS1591
        Dark,
        #pragma warning restore CS1591
        [EnumMember(Value = "light")]
        #pragma warning disable CS1591
        Light,
        #pragma warning restore CS1591
    }
}
