// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>
    /// Composed type wrapper for classes <see cref="global::Soenneker.Adyen.OpenApiClient.Models.ConfirmationTrackingData"/>, <see cref="global::Soenneker.Adyen.OpenApiClient.Models.EstimationTrackingData"/>, <see cref="global::Soenneker.Adyen.OpenApiClient.Models.InternalReviewTrackingData"/>
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class TransferDataTracking : IComposedTypeWrapper, IParsable
    {
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Adyen.OpenApiClient.Models.ConfirmationTrackingData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.ConfirmationTrackingData? ConfirmationTrackingData { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.ConfirmationTrackingData ConfirmationTrackingData { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Adyen.OpenApiClient.Models.EstimationTrackingData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.EstimationTrackingData? EstimationTrackingData { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.EstimationTrackingData EstimationTrackingData { get; set; }
#endif
        /// <summary>Composed type representation for type <see cref="global::Soenneker.Adyen.OpenApiClient.Models.InternalReviewTrackingData"/></summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.InternalReviewTrackingData? InternalReviewTrackingData { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.InternalReviewTrackingData InternalReviewTrackingData { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.TransferDataTracking"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.TransferDataTracking CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            var mappingValue = parseNode.GetChildNode("type")?.GetStringValue();
            var result = new global::Soenneker.Adyen.OpenApiClient.Models.TransferDataTracking();
            if("confirmation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.ConfirmationTrackingData = new global::Soenneker.Adyen.OpenApiClient.Models.ConfirmationTrackingData();
            }
            else if("estimation".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.EstimationTrackingData = new global::Soenneker.Adyen.OpenApiClient.Models.EstimationTrackingData();
            }
            else if("internalReview".Equals(mappingValue, StringComparison.OrdinalIgnoreCase))
            {
                result.InternalReviewTrackingData = new global::Soenneker.Adyen.OpenApiClient.Models.InternalReviewTrackingData();
            }
            return result;
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            if(ConfirmationTrackingData != null)
            {
                return ConfirmationTrackingData.GetFieldDeserializers();
            }
            else if(EstimationTrackingData != null)
            {
                return EstimationTrackingData.GetFieldDeserializers();
            }
            else if(InternalReviewTrackingData != null)
            {
                return InternalReviewTrackingData.GetFieldDeserializers();
            }
            return new Dictionary<string, Action<IParseNode>>();
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            if(ConfirmationTrackingData != null)
            {
                writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.ConfirmationTrackingData>(null, ConfirmationTrackingData);
            }
            else if(EstimationTrackingData != null)
            {
                writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.EstimationTrackingData>(null, EstimationTrackingData);
            }
            else if(InternalReviewTrackingData != null)
            {
                writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.InternalReviewTrackingData>(null, InternalReviewTrackingData);
            }
        }
    }
}
#pragma warning restore CS0618
