// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransactionRule : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>&quot;The level at which data must be accumulated, used in rules with `type` **velocity** or **maxUsage**. The level must be the [same or lower in hierarchy](https://docs.adyen.com/issuing/transaction-rules#accumulate-data) than the `entityKey`.If not provided, by default, the rule will accumulate data at the **paymentInstrument** level.Possible values: **paymentInstrument**, **paymentInstrumentGroup**, **balanceAccount**, **accountHolder**, **balancePlatform**.&quot;</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? AggregationLevel { get; set; }
#nullable restore
#else
        public string AggregationLevel { get; set; }
#endif
        /// <summary>Your description for the transaction rule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Description { get; set; }
#nullable restore
#else
        public string Description { get; set; }
#endif
        /// <summary>The date when the rule will stop being evaluated, in ISO 8601 extended offset date-time format. For example, **2025-03-19T10:15:30+01:00**.If not provided, the rule will be evaluated until the rule status is set to **inactive**.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? EndDate { get; set; }
#nullable restore
#else
        public string EndDate { get; set; }
#endif
        /// <summary>The entityKey property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.TransactionRuleEntityKey? EntityKey { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.TransactionRuleEntityKey EntityKey { get; set; }
#endif
        /// <summary>The unique identifier of the transaction rule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The interval property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.TransactionRuleInterval? Interval { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.TransactionRuleInterval Interval { get; set; }
#endif
        /// <summary>&quot;The [outcome](https://docs.adyen.com/issuing/transaction-rules#outcome) that will be applied when a transaction meets the conditions of the rule.Possible values:* **hardBlock** (default): the transaction is declined.* **scoreBased**: the transaction is assigned the `score` you specified. Adyen calculates the total score and if it exceeds 100, the transaction is declined. This value is not allowed when `requestType` is **bankTransfer**.* **enforceSCA**: your user is prompted to verify their identity using [3D Secure authentication](https://docs.adyen.com/issuing/3d-secure/). If the authentication fails or times out, the transaction is declined. This value is only allowed when `requestType` is **authentication**.&quot;</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule_outcomeType? OutcomeType { get; set; }
        /// <summary>&quot;Specifies the reason for creating the rule.Possible values:* **fraud**: the rule is created to regulate fraudulent activity.* **policy**: the rule is created to ensure that the transaction adheres to your business&apos; policies. For example, if your business has policies about the Merchant Category Codes (MCCs) allowed on a transaction, you can create a rule to block transactions that have specific MCCs.&quot;</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule_purpose? Purpose { get; set; }
        /// <summary>Your reference for the transaction rule.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Reference { get; set; }
#nullable restore
#else
        public string Reference { get; set; }
#endif
        /// <summary>&quot;Indicates the type of request to which the rule applies. If not provided, by default, this is set to **authorization**.Possible values: **authorization**, **authentication**, **tokenization**, **bankTransfer**.&quot;</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule_requestType? RequestType { get; set; }
        /// <summary>The ruleRestrictions property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.TransactionRuleRestrictions? RuleRestrictions { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.TransactionRuleRestrictions RuleRestrictions { get; set; }
#endif
        /// <summary>A positive or negative score applied to the transaction if it meets the conditions of the rule. Required when `outcomeType` is **scoreBased**.  The value must be between **-100** and **100**.</summary>
        public int? Score { get; set; }
        /// <summary>The date when the rule will start to be evaluated, in ISO 8601 extended offset date-time format. For example, **2025-03-19T10:15:30+01:00**.If not provided when creating a transaction rule, the `startDate` is set to the date when the rule status is set to **active**. </summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StartDate { get; set; }
#nullable restore
#else
        public string StartDate { get; set; }
#endif
        /// <summary>&quot;The status of the transaction rule. If you provide a `startDate` in the request, the rule is automatically created with an **active** status. Possible values: **active**, **inactive**.&quot;</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule_status? Status { get; set; }
        /// <summary>&quot;The [type of rule](https://docs.adyen.com/issuing/transaction-rules#rule-types), which defines if a rule blocks transactions based on individual characteristics or accumulates data.Possible values: * **blockList**: decline a transaction when the conditions are met. * **maxUsage**: add the amount or number of transactions for the lifetime of a payment instrument, and then decline a transaction when the specified limits are met. * **velocity**: add the amount or number of transactions based on a specified time interval, and then decline a transaction when the specified limits are met.&quot;</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule_type? Type { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "aggregationLevel", n => { AggregationLevel = n.GetStringValue(); } },
                { "description", n => { Description = n.GetStringValue(); } },
                { "endDate", n => { EndDate = n.GetStringValue(); } },
                { "entityKey", n => { EntityKey = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRuleEntityKey>(global::Soenneker.Adyen.OpenApiClient.Models.TransactionRuleEntityKey.CreateFromDiscriminatorValue); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "interval", n => { Interval = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRuleInterval>(global::Soenneker.Adyen.OpenApiClient.Models.TransactionRuleInterval.CreateFromDiscriminatorValue); } },
                { "outcomeType", n => { OutcomeType = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule_outcomeType>(); } },
                { "purpose", n => { Purpose = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule_purpose>(); } },
                { "reference", n => { Reference = n.GetStringValue(); } },
                { "requestType", n => { RequestType = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule_requestType>(); } },
                { "ruleRestrictions", n => { RuleRestrictions = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRuleRestrictions>(global::Soenneker.Adyen.OpenApiClient.Models.TransactionRuleRestrictions.CreateFromDiscriminatorValue); } },
                { "score", n => { Score = n.GetIntValue(); } },
                { "startDate", n => { StartDate = n.GetStringValue(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule_status>(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule_type>(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("aggregationLevel", AggregationLevel);
            writer.WriteStringValue("description", Description);
            writer.WriteStringValue("endDate", EndDate);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRuleEntityKey>("entityKey", EntityKey);
            writer.WriteStringValue("id", Id);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRuleInterval>("interval", Interval);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule_outcomeType>("outcomeType", OutcomeType);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule_purpose>("purpose", Purpose);
            writer.WriteStringValue("reference", Reference);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule_requestType>("requestType", RequestType);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRuleRestrictions>("ruleRestrictions", RuleRestrictions);
            writer.WriteIntValue("score", Score);
            writer.WriteStringValue("startDate", StartDate);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule_status>("status", Status);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransactionRule_type>("type", Type);
        }
    }
}
#pragma warning restore CS0618
