// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class TransferEvent : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The amount adjustments in this transfer.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Adyen.OpenApiClient.Models.AmountAdjustment>? AmountAdjustments { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Adyen.OpenApiClient.Models.AmountAdjustment> AmountAdjustments { get; set; }
#endif
        /// <summary>The date when the transfer request was sent.</summary>
        public DateTimeOffset? BookingDate { get; set; }
        /// <summary>The unique identifier of the transfer event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Id { get; set; }
#nullable restore
#else
        public string Id { get; set; }
#endif
        /// <summary>The list of the balance mutation per event.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::Soenneker.Adyen.OpenApiClient.Models.BalanceMutation>? Mutations { get; set; }
#nullable restore
#else
        public List<global::Soenneker.Adyen.OpenApiClient.Models.BalanceMutation> Mutations { get; set; }
#endif
        /// <summary>The amount in the original currency.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.TransferEventOriginalAmount? OriginalAmount { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.TransferEventOriginalAmount OriginalAmount { get; set; }
#endif
        /// <summary>The reason for the transfer status.</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.TransferEventReason? Reason { get; set; }
        /// <summary>The status of the transfer event.</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.TransferEventStatus? Status { get; set; }
        /// <summary>The id of the transaction that is related to this accounting event. Only sent for events of type **accounting** where the balance changes.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? TransactionId { get; set; }
#nullable restore
#else
        public string TransactionId { get; set; }
#endif
        /// <summary>The type of the transfer event. Possible values: **accounting**, **tracking**.</summary>
        public global::Soenneker.Adyen.OpenApiClient.Models.TransferEventType? Type { get; set; }
        /// <summary>The date when the tracking status was updated.</summary>
        public DateTimeOffset? UpdateDate { get; set; }
        /// <summary>A future date, when the funds are expected to be deducted from or credited to the balance account.</summary>
        public DateTimeOffset? ValueDate { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.Models.TransferEvent"/> and sets the default values.
        /// </summary>
        public TransferEvent()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.TransferEvent"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.TransferEvent CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.TransferEvent();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "amountAdjustments", n => { AmountAdjustments = n.GetCollectionOfObjectValues<global::Soenneker.Adyen.OpenApiClient.Models.AmountAdjustment>(global::Soenneker.Adyen.OpenApiClient.Models.AmountAdjustment.CreateFromDiscriminatorValue)?.AsList(); } },
                { "bookingDate", n => { BookingDate = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetStringValue(); } },
                { "mutations", n => { Mutations = n.GetCollectionOfObjectValues<global::Soenneker.Adyen.OpenApiClient.Models.BalanceMutation>(global::Soenneker.Adyen.OpenApiClient.Models.BalanceMutation.CreateFromDiscriminatorValue)?.AsList(); } },
                { "originalAmount", n => { OriginalAmount = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.TransferEventOriginalAmount>(global::Soenneker.Adyen.OpenApiClient.Models.TransferEventOriginalAmount.CreateFromDiscriminatorValue); } },
                { "reason", n => { Reason = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransferEventReason>(); } },
                { "status", n => { Status = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransferEventStatus>(); } },
                { "transactionId", n => { TransactionId = n.GetStringValue(); } },
                { "type", n => { Type = n.GetEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransferEventType>(); } },
                { "updateDate", n => { UpdateDate = n.GetDateTimeOffsetValue(); } },
                { "valueDate", n => { ValueDate = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteCollectionOfObjectValues<global::Soenneker.Adyen.OpenApiClient.Models.AmountAdjustment>("amountAdjustments", AmountAdjustments);
            writer.WriteDateTimeOffsetValue("bookingDate", BookingDate);
            writer.WriteStringValue("id", Id);
            writer.WriteCollectionOfObjectValues<global::Soenneker.Adyen.OpenApiClient.Models.BalanceMutation>("mutations", Mutations);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.TransferEventOriginalAmount>("originalAmount", OriginalAmount);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransferEventReason>("reason", Reason);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransferEventStatus>("status", Status);
            writer.WriteStringValue("transactionId", TransactionId);
            writer.WriteEnumValue<global::Soenneker.Adyen.OpenApiClient.Models.TransferEventType>("type", Type);
            writer.WriteDateTimeOffsetValue("updateDate", UpdateDate);
            writer.WriteDateTimeOffsetValue("valueDate", ValueDate);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
