// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>&quot;The type of tracking event. Possible values:  - **internalReview**: the transfer was flagged because it does not comply with Adyen&apos;s risk policy.&quot;</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TransferServiceV4InternalReviewTrackingData_type
    {
        [EnumMember(Value = "internalReview")]
        #pragma warning disable CS1591
        InternalReview,
        #pragma warning restore CS1591
    }
}
