// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>The type of transfer instrument.Possible value: **bankAccount**.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum TransferInstrumentType
    {
        [EnumMember(Value = "bankAccount")]
        #pragma warning disable CS1591
        BankAccount,
        #pragma warning restore CS1591
        [EnumMember(Value = "recurringDetail")]
        #pragma warning disable CS1591
        RecurringDetail,
        #pragma warning restore CS1591
    }
}
