// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class UpdatePaymentMethodInfo : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The accel property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.AccelUpdateInfo? Accel { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.AccelUpdateInfo Accel { get; set; }
#endif
        /// <summary>The affirm property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.AffirmUpdateInfo? Affirm { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.AffirmUpdateInfo Affirm { get; set; }
#endif
        /// <summary>The bcmc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.BcmcUpdateInfo? Bcmc { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.BcmcUpdateInfo Bcmc { get; set; }
#endif
        /// <summary>The carnet property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo? Carnet { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo Carnet { get; set; }
#endif
        /// <summary>The cartesBancaires property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.CartesBancairesUpdateInfo? CartesBancaires { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.CartesBancairesUpdateInfo CartesBancaires { get; set; }
#endif
        /// <summary>The list of countries where a payment method is available. By default, all countries supported by the payment method.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Countries { get; set; }
#nullable restore
#else
        public List<string> Countries { get; set; }
#endif
        /// <summary>The cup property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo? Cup { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo Cup { get; set; }
#endif
        /// <summary>The list of currencies that a payment method supports. By default, all currencies supported by the payment method.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Currencies { get; set; }
#nullable restore
#else
        public List<string> Currencies { get; set; }
#endif
        /// <summary>Custom routing flags for acquirer routing.</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? CustomRoutingFlags { get; set; }
#nullable restore
#else
        public List<string> CustomRoutingFlags { get; set; }
#endif
        /// <summary>The diners property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo? Diners { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo Diners { get; set; }
#endif
        /// <summary>The discover property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo? Discover { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo Discover { get; set; }
#endif
        /// <summary>The eft_directdebit_CA property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo? EftDirectdebitCA { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo EftDirectdebitCA { get; set; }
#endif
        /// <summary>The eftpos_australia property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo? EftposAustralia { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo EftposAustralia { get; set; }
#endif
        /// <summary>Indicates whether the payment method is enabled (**true**) or disabled (**false**).</summary>
        public bool? Enabled { get; set; }
        /// <summary>The girocard property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo? Girocard { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo Girocard { get; set; }
#endif
        /// <summary>The ideal property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo? Ideal { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo Ideal { get; set; }
#endif
        /// <summary>The interac_card property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo? InteracCard { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo InteracCard { get; set; }
#endif
        /// <summary>The jcb property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo? Jcb { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo Jcb { get; set; }
#endif
        /// <summary>The maestro property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo? Maestro { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo Maestro { get; set; }
#endif
        /// <summary>The maestro_usa property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo? MaestroUsa { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo MaestroUsa { get; set; }
#endif
        /// <summary>The mc property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo? Mc { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo Mc { get; set; }
#endif
        /// <summary>The nyce property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.NyceUpdateInfo? Nyce { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.NyceUpdateInfo Nyce { get; set; }
#endif
        /// <summary>The paybybank_plaid property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PayByBankPlaidUpdateInfo? PaybybankPlaid { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PayByBankPlaidUpdateInfo PaybybankPlaid { get; set; }
#endif
        /// <summary>The pulse property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.PulseUpdateInfo? Pulse { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.PulseUpdateInfo Pulse { get; set; }
#endif
        /// <summary>The sepadirectdebit property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.SepaDirectDebitUpdateInfo? Sepadirectdebit { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.SepaDirectDebitUpdateInfo Sepadirectdebit { get; set; }
#endif
        /// <summary>The star property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.StarUpdateInfo? Star { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.StarUpdateInfo Star { get; set; }
#endif
        /// <summary>The store for this payment method</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? StoreId { get; set; }
#nullable restore
#else
        public string StoreId { get; set; }
#endif
        /// <summary>The list of stores for this payment method</summary>
        [Obsolete("")]
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? StoreIds { get; set; }
#nullable restore
#else
        public List<string> StoreIds { get; set; }
#endif
        /// <summary>The visa property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo? Visa { get; set; }
#nullable restore
#else
        public global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo Visa { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.UpdatePaymentMethodInfo"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Soenneker.Adyen.OpenApiClient.Models.UpdatePaymentMethodInfo CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            if(ReferenceEquals(parseNode, null)) throw new ArgumentNullException(nameof(parseNode));
            return new global::Soenneker.Adyen.OpenApiClient.Models.UpdatePaymentMethodInfo();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "accel", n => { Accel = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.AccelUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.AccelUpdateInfo.CreateFromDiscriminatorValue); } },
                { "affirm", n => { Affirm = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.AffirmUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.AffirmUpdateInfo.CreateFromDiscriminatorValue); } },
                { "bcmc", n => { Bcmc = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.BcmcUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.BcmcUpdateInfo.CreateFromDiscriminatorValue); } },
                { "carnet", n => { Carnet = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo.CreateFromDiscriminatorValue); } },
                { "cartesBancaires", n => { CartesBancaires = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CartesBancairesUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.CartesBancairesUpdateInfo.CreateFromDiscriminatorValue); } },
                { "countries", n => { Countries = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "cup", n => { Cup = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo.CreateFromDiscriminatorValue); } },
                { "currencies", n => { Currencies = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "customRoutingFlags", n => { CustomRoutingFlags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "diners", n => { Diners = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo.CreateFromDiscriminatorValue); } },
                { "discover", n => { Discover = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo.CreateFromDiscriminatorValue); } },
                { "eft_directdebit_CA", n => { EftDirectdebitCA = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo.CreateFromDiscriminatorValue); } },
                { "eftpos_australia", n => { EftposAustralia = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo.CreateFromDiscriminatorValue); } },
                { "enabled", n => { Enabled = n.GetBoolValue(); } },
                { "girocard", n => { Girocard = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo.CreateFromDiscriminatorValue); } },
                { "ideal", n => { Ideal = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo.CreateFromDiscriminatorValue); } },
                { "interac_card", n => { InteracCard = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo.CreateFromDiscriminatorValue); } },
                { "jcb", n => { Jcb = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo.CreateFromDiscriminatorValue); } },
                { "maestro", n => { Maestro = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo.CreateFromDiscriminatorValue); } },
                { "maestro_usa", n => { MaestroUsa = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo.CreateFromDiscriminatorValue); } },
                { "mc", n => { Mc = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo.CreateFromDiscriminatorValue); } },
                { "nyce", n => { Nyce = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.NyceUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.NyceUpdateInfo.CreateFromDiscriminatorValue); } },
                { "paybybank_plaid", n => { PaybybankPlaid = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PayByBankPlaidUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.PayByBankPlaidUpdateInfo.CreateFromDiscriminatorValue); } },
                { "pulse", n => { Pulse = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PulseUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.PulseUpdateInfo.CreateFromDiscriminatorValue); } },
                { "sepadirectdebit", n => { Sepadirectdebit = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.SepaDirectDebitUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.SepaDirectDebitUpdateInfo.CreateFromDiscriminatorValue); } },
                { "star", n => { Star = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.StarUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.StarUpdateInfo.CreateFromDiscriminatorValue); } },
                { "storeId", n => { StoreId = n.GetStringValue(); } },
                { "storeIds", n => { StoreIds = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "visa", n => { Visa = n.GetObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>(global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            if(ReferenceEquals(writer, null)) throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.AccelUpdateInfo>("accel", Accel);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.AffirmUpdateInfo>("affirm", Affirm);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.BcmcUpdateInfo>("bcmc", Bcmc);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>("carnet", Carnet);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.CartesBancairesUpdateInfo>("cartesBancaires", CartesBancaires);
            writer.WriteCollectionOfPrimitiveValues<string>("countries", Countries);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>("cup", Cup);
            writer.WriteCollectionOfPrimitiveValues<string>("currencies", Currencies);
            writer.WriteCollectionOfPrimitiveValues<string>("customRoutingFlags", CustomRoutingFlags);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>("diners", Diners);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>("discover", Discover);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>("eft_directdebit_CA", EftDirectdebitCA);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>("eftpos_australia", EftposAustralia);
            writer.WriteBoolValue("enabled", Enabled);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>("girocard", Girocard);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>("ideal", Ideal);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>("interac_card", InteracCard);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>("jcb", Jcb);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>("maestro", Maestro);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>("maestro_usa", MaestroUsa);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>("mc", Mc);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.NyceUpdateInfo>("nyce", Nyce);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PayByBankPlaidUpdateInfo>("paybybank_plaid", PaybybankPlaid);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.PulseUpdateInfo>("pulse", Pulse);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.SepaDirectDebitUpdateInfo>("sepadirectdebit", Sepadirectdebit);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.StarUpdateInfo>("star", Star);
            writer.WriteStringValue("storeId", StoreId);
            writer.WriteCollectionOfPrimitiveValues<string>("storeIds", StoreIds);
            writer.WriteObjectValue<global::Soenneker.Adyen.OpenApiClient.Models.GenericPmWithTdiUpdateInfo>("visa", Visa);
        }
    }
}
#pragma warning restore CS0618
