// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Soenneker.Adyen.OpenApiClient.Models
{
    /// <summary>**visacheckout**</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum VisaCheckoutDetails_type
    {
        [EnumMember(Value = "visacheckout")]
        #pragma warning disable CS1591
        Visacheckout,
        #pragma warning restore CS1591
    }
}
