// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Adyen.OpenApiClient.CloudDeviceServiceV1.Merchants.Item.Devices.Item.Async;
using Soenneker.Adyen.OpenApiClient.CloudDeviceServiceV1.Merchants.Item.Devices.Item.Status;
using Soenneker.Adyen.OpenApiClient.CloudDeviceServiceV1.Merchants.Item.Devices.Item.Sync;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Adyen.OpenApiClient.CloudDeviceServiceV1.Merchants.Item.Devices.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \CloudDeviceService-v1\merchants\{merchantAccount}\devices\{deviceId}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class WithDeviceItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The async property</summary>
        public global::Soenneker.Adyen.OpenApiClient.CloudDeviceServiceV1.Merchants.Item.Devices.Item.Async.AsyncRequestBuilder Async
        {
            get => new global::Soenneker.Adyen.OpenApiClient.CloudDeviceServiceV1.Merchants.Item.Devices.Item.Async.AsyncRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The status property</summary>
        public global::Soenneker.Adyen.OpenApiClient.CloudDeviceServiceV1.Merchants.Item.Devices.Item.Status.StatusRequestBuilder Status
        {
            get => new global::Soenneker.Adyen.OpenApiClient.CloudDeviceServiceV1.Merchants.Item.Devices.Item.Status.StatusRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The sync property</summary>
        public global::Soenneker.Adyen.OpenApiClient.CloudDeviceServiceV1.Merchants.Item.Devices.Item.Sync.SyncRequestBuilder Sync
        {
            get => new global::Soenneker.Adyen.OpenApiClient.CloudDeviceServiceV1.Merchants.Item.Devices.Item.Sync.SyncRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.CloudDeviceServiceV1.Merchants.Item.Devices.Item.WithDeviceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDeviceItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CloudDeviceService-v1/merchants/{merchantAccount}/devices/{deviceId}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.CloudDeviceServiceV1.Merchants.Item.Devices.Item.WithDeviceItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public WithDeviceItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/CloudDeviceService-v1/merchants/{merchantAccount}/devices/{deviceId}", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
