// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Adyen.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Companies.Item.ClientCertificates
{
    /// <summary>
    /// Builds and executes requests for operations under \ManagementService-v3\companies\{companyId}\clientCertificates
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class ClientCertificatesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Companies.Item.ClientCertificates.ClientCertificatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClientCertificatesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ManagementService-v3/companies/{companyId}/clientCertificates", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Companies.Item.ClientCertificates.ClientCertificatesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public ClientCertificatesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/ManagementService-v3/companies/{companyId}/clientCertificates", rawUrl)
        {
        }
        /// <summary>
        /// Retrieve all previously issued client certificates under this company account which are still valid (neither expired nor revoked).To make this request, your API credential must have the following [roles](https://docs.adyen.com/development-resources/api-credentials#api-permissions):* Management API - Client certificates read
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.CertificateSearchResponse"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Adyen.OpenApiClient.Models.CertificateSearchResponse?> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Adyen.OpenApiClient.Models.CertificateSearchResponse> GetAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "401", global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Adyen.OpenApiClient.Models.CertificateSearchResponse>(requestInfo, global::Soenneker.Adyen.OpenApiClient.Models.CertificateSearchResponse.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Generates a client certificate for secure communication with Adyen using mutual TLS (mTLS). Provide a certificate signing request (CSR). Adyen signs it and returns the client certificate.The CSR must be generated by a key pair that meets the following criteria:* Key ownership: the CSR must be signed by the associated private key.* Key type: RSA with a minimum key size of 2048 bits, or ECC with a minimum key size of 224 bits.A company account can have a maximum of 10 valid client certificates at a time.The subject distinguished name (`subjectDN`) of the issued certificate is constructed by Adyen from the path `companyId` and the request `apiCredential`. The subject in your CSR is not used. The returned `subjectDN` has the format `UID={apiCredential}-Company.{companyId},CN={apiCredential}-Company.{companyId},O=Company.{companyId}`.To make this request, your API credential must have the following [roles](https://docs.adyen.com/development-resources/api-credentials#api-permissions):* Management API - Client certificates read and write
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.ClientCertificateWithChain"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity">When receiving a 429 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Adyen.OpenApiClient.Models.ClientCertificateWithChain?> PostAsync(global::Soenneker.Adyen.OpenApiClient.Models.ClientCertificateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Adyen.OpenApiClient.Models.ClientCertificateWithChain> PostAsync(global::Soenneker.Adyen.OpenApiClient.Models.ClientCertificateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPostRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity.CreateFromDiscriminatorValue },
                { "429", global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Adyen.OpenApiClient.Models.ManagementServiceV3DefaultErrorResponseEntity.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Adyen.OpenApiClient.Models.ClientCertificateWithChain>(requestInfo, global::Soenneker.Adyen.OpenApiClient.Models.ClientCertificateWithChain.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// Retrieve all previously issued client certificates under this company account which are still valid (neither expired nor revoked).To make this request, your API credential must have the following [roles](https://docs.adyen.com/development-resources/api-credentials#api-permissions):* Management API - Client certificates read
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// Generates a client certificate for secure communication with Adyen using mutual TLS (mTLS). Provide a certificate signing request (CSR). Adyen signs it and returns the client certificate.The CSR must be generated by a key pair that meets the following criteria:* Key ownership: the CSR must be signed by the associated private key.* Key type: RSA with a minimum key size of 2048 bits, or ECC with a minimum key size of 224 bits.A company account can have a maximum of 10 valid client certificates at a time.The subject distinguished name (`subjectDN`) of the issued certificate is constructed by Adyen from the path `companyId` and the request `apiCredential`. The subject in your CSR is not used. The returned `subjectDN` has the format `UID={apiCredential}-Company.{companyId},CN={apiCredential}-Company.{companyId},O=Company.{companyId}`.To make this request, your API credential must have the following [roles](https://docs.adyen.com/development-resources/api-credentials#api-permissions):* Management API - Client certificates read and write
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPostRequestInformation(global::Soenneker.Adyen.OpenApiClient.Models.ClientCertificateRequest body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPostRequestInformation(global::Soenneker.Adyen.OpenApiClient.Models.ClientCertificateRequest body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.POST, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Companies.Item.ClientCertificates.ClientCertificatesRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Companies.Item.ClientCertificates.ClientCertificatesRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Adyen.OpenApiClient.ManagementServiceV3.Companies.Item.ClientCertificates.ClientCertificatesRequestBuilder(rawUrl, RequestAdapter);
        }
    }
}
#pragma warning restore CS0618
