// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using Microsoft.Kiota.Abstractions;
using Soenneker.Adyen.OpenApiClient.Models;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System.Threading;
using System;
namespace Soenneker.Adyen.OpenApiClient.LegalEntityServiceV4.Documents.Item
{
    /// <summary>
    /// Builds and executes requests for operations under \LegalEntityService-v4\documents\{id}
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DocumentsItemRequestBuilder : BaseRequestBuilder
    {
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.LegalEntityServiceV4.Documents.Item.DocumentsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DocumentsItemRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/LegalEntityService-v4/documents/{id}{?skipContent*}", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.LegalEntityServiceV4.Documents.Item.DocumentsItemRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DocumentsItemRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/LegalEntityService-v4/documents/{id}{?skipContent*}", rawUrl)
        {
        }
        /// <summary>
        /// &quot;Deletes a document.Requests to this endpoint are subject to rate limits:- Live environments: 700 requests per 5 seconds.- Test environments: 200 requests per 5 seconds.- Failed requests are subject to a limit of 5 failures per 10 seconds.&quot;
        /// </summary>
        /// <returns>A <see cref="Stream"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<Stream?> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<Stream> DeleteAsync(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToDeleteRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendPrimitiveAsync<Stream>(requestInfo, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Returns a document.Requests to this endpoint are subject to rate limits:- Live environments: 700 requests per 5 seconds.- Test environments: 200 requests per 5 seconds.- Failed requests are subject to a limit of 5 failures per 10 seconds.&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.Document"/></returns>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Adyen.OpenApiClient.Models.Document?> GetAsync(Action<RequestConfiguration<global::Soenneker.Adyen.OpenApiClient.LegalEntityServiceV4.Documents.Item.DocumentsItemRequestBuilder.DocumentsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Adyen.OpenApiClient.Models.Document> GetAsync(Action<RequestConfiguration<global::Soenneker.Adyen.OpenApiClient.LegalEntityServiceV4.Documents.Item.DocumentsItemRequestBuilder.DocumentsItemRequestBuilderGetQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            var requestInfo = ToGetRequestInformation(requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Adyen.OpenApiClient.Models.Document>(requestInfo, global::Soenneker.Adyen.OpenApiClient.Models.Document.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Updates a document. &gt;You can upload a maximum of 15 pages for photo IDs.Requests to this endpoint are subject to rate limits:- Live environments: 700 requests per 5 seconds.- Test environments: 200 requests per 5 seconds.- Failed requests are subject to a limit of 5 failures per 10 seconds.&quot;
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.Models.Document"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="cancellationToken">Cancellation token to use when cancelling requests</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError">When receiving a 400 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError">When receiving a 401 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError">When receiving a 403 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError">When receiving a 422 status code</exception>
        /// <exception cref="global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError">When receiving a 500 status code</exception>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public async Task<global::Soenneker.Adyen.OpenApiClient.Models.Document?> PatchAsync(global::Soenneker.Adyen.OpenApiClient.Models.Document body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#nullable restore
#else
        public async Task<global::Soenneker.Adyen.OpenApiClient.Models.Document> PatchAsync(global::Soenneker.Adyen.OpenApiClient.Models.Document body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default, CancellationToken cancellationToken = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = ToPatchRequestInformation(body, requestConfiguration);
            var errorMapping = new Dictionary<string, ParsableFactory<IParsable>>
            {
                { "400", global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError.CreateFromDiscriminatorValue },
                { "401", global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError.CreateFromDiscriminatorValue },
                { "403", global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError.CreateFromDiscriminatorValue },
                { "422", global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError.CreateFromDiscriminatorValue },
                { "500", global::Soenneker.Adyen.OpenApiClient.Models.LegalEntityServiceV4ServiceError.CreateFromDiscriminatorValue },
            };
            return await RequestAdapter.SendAsync<global::Soenneker.Adyen.OpenApiClient.Models.Document>(requestInfo, global::Soenneker.Adyen.OpenApiClient.Models.Document.CreateFromDiscriminatorValue, errorMapping, cancellationToken).ConfigureAwait(false);
        }
        /// <summary>
        /// &quot;Deletes a document.Requests to this endpoint are subject to rate limits:- Live environments: 700 requests per 5 seconds.- Test environments: 200 requests per 5 seconds.- Failed requests are subject to a limit of 5 failures per 10 seconds.&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToDeleteRequestInformation(Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.DELETE, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// &quot;Returns a document.Requests to this endpoint are subject to rate limits:- Live environments: 700 requests per 5 seconds.- Test environments: 200 requests per 5 seconds.- Failed requests are subject to a limit of 5 failures per 10 seconds.&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Adyen.OpenApiClient.LegalEntityServiceV4.Documents.Item.DocumentsItemRequestBuilder.DocumentsItemRequestBuilderGetQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToGetRequestInformation(Action<RequestConfiguration<global::Soenneker.Adyen.OpenApiClient.LegalEntityServiceV4.Documents.Item.DocumentsItemRequestBuilder.DocumentsItemRequestBuilderGetQueryParameters>> requestConfiguration = default)
        {
#endif
            var requestInfo = new RequestInformation(Method.GET, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            return requestInfo;
        }
        /// <summary>
        /// &quot;Updates a document. &gt;You can upload a maximum of 15 pages for photo IDs.Requests to this endpoint are subject to rate limits:- Live environments: 700 requests per 5 seconds.- Test environments: 200 requests per 5 seconds.- Failed requests are subject to a limit of 5 failures per 10 seconds.&quot;
        /// </summary>
        /// <returns>A <see cref="RequestInformation"/></returns>
        /// <param name="body">The request body</param>
        /// <param name="requestConfiguration">Configuration for the request such as headers, query parameters, and middleware options.</param>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Adyen.OpenApiClient.Models.Document body, Action<RequestConfiguration<DefaultQueryParameters>>? requestConfiguration = default)
        {
#nullable restore
#else
        public RequestInformation ToPatchRequestInformation(global::Soenneker.Adyen.OpenApiClient.Models.Document body, Action<RequestConfiguration<DefaultQueryParameters>> requestConfiguration = default)
        {
#endif
            if(ReferenceEquals(body, null)) throw new ArgumentNullException(nameof(body));
            var requestInfo = new RequestInformation(Method.PATCH, UrlTemplate, PathParameters);
            requestInfo.Configure(requestConfiguration);
            requestInfo.Headers.TryAdd("Accept", "application/json");
            requestInfo.SetContentFromParsable(RequestAdapter, "application/json", body);
            return requestInfo;
        }
        /// <summary>
        /// Returns a request builder with the provided arbitrary URL. Using this method means any other path or query parameters are ignored.
        /// </summary>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.LegalEntityServiceV4.Documents.Item.DocumentsItemRequestBuilder"/></returns>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        public global::Soenneker.Adyen.OpenApiClient.LegalEntityServiceV4.Documents.Item.DocumentsItemRequestBuilder WithUrl(string rawUrl)
        {
            return new global::Soenneker.Adyen.OpenApiClient.LegalEntityServiceV4.Documents.Item.DocumentsItemRequestBuilder(rawUrl, RequestAdapter);
        }
        /// <summary>
        /// &quot;Returns a document.Requests to this endpoint are subject to rate limits:- Live environments: 700 requests per 5 seconds.- Test environments: 200 requests per 5 seconds.- Failed requests are subject to a limit of 5 failures per 10 seconds.&quot;
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
        public partial class DocumentsItemRequestBuilderGetQueryParameters 
        {
            /// <summary>Do not load document content while fetching the document.</summary>
            [QueryParameter("skipContent")]
            public bool? SkipContent { get; set; }
        }
    }
}
#pragma warning restore CS0618
