// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using Soenneker.Adyen.OpenApiClient.BalanceControlServiceV2.BalanceOverview.Companies.Item;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace Soenneker.Adyen.OpenApiClient.BalanceControlServiceV2.BalanceOverview.Companies
{
    /// <summary>
    /// Builds and executes requests for operations under \BalanceControlService-v2\balanceOverview\companies
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class CompaniesRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the Soenneker.Adyen.OpenApiClient.BalanceControlServiceV2.balanceOverview.companies.item collection</summary>
        /// <param name="position">The unique identifier of your company account.</param>
        /// <returns>A <see cref="global::Soenneker.Adyen.OpenApiClient.BalanceControlServiceV2.BalanceOverview.Companies.Item.WithCompanyAccountCodeItemRequestBuilder"/></returns>
        public global::Soenneker.Adyen.OpenApiClient.BalanceControlServiceV2.BalanceOverview.Companies.Item.WithCompanyAccountCodeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("companyAccountCode", position);
                return new global::Soenneker.Adyen.OpenApiClient.BalanceControlServiceV2.BalanceOverview.Companies.Item.WithCompanyAccountCodeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.BalanceControlServiceV2.BalanceOverview.Companies.CompaniesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompaniesRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/BalanceControlService-v2/balanceOverview/companies", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::Soenneker.Adyen.OpenApiClient.BalanceControlServiceV2.BalanceOverview.Companies.CompaniesRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public CompaniesRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/BalanceControlService-v2/balanceOverview/companies", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
